### ISSUE TITLE
How to disable `orderless` for  some specific regions or type of hints?

### ISSUE THREAD

**Issue by hongyi-zhao** [oantolin/orderless#101]
On Ubuntu 20.04.3 LTS, I use the latest self-compiled git master version of Emacs and the following `orderless` configuration:
```emacs-lisp
(use-package orderless
  :config
  (setq
   ;; https://github.com/oantolin/orderless#ivy
   ivy-re-builders-alist '((t . orderless-ivy-re-builder))

   ;; Configure a custom style dispatcher (see the Consult wiki)
   ;; orderless-style-dispatchers '(+orderless-dispatch)
   ;; orderless-component-separator #'orderless-escapable-split-on-space

   completion-styles '(orderless)
   completion-category-defaults nil
   completion-category-overrides '((file (styles . (partial-completion)))))
  )
```

This produces some undesirable results, such as the following candidate list when I want to enter a `use-package`:

![image](https://user-images.githubusercontent.com/11155854/145145109-34c8e2e0-6011-4ff1-8b01-d71ffb418c85.png)

As you can see, this will make my selection of target candidates more difficult than convenient. Any hints for disabling the `orderless` for some specific regions/hints, say the above one?

Regards,
HZ

**Comment by oantolin** [comment]
You can just advise `company-calculate-candidates` to use any completion styles you prefer:

```elisp
(defun without-orderless (fn &rest args)
  (let ((completion-styles '(partial-completion)))
    (apply fn args)))

(advice-add 'company-calculate-candidates :around #'without-orderless)
```

Instead of disabling orderless you could alternatively add a style dispatcher that automatically anchors the first component using `^`. If you don't want to use it all the time, you can set things up so that it only is used for company:

```elisp
(defun anchor-first-component (pattern index _total)
  (when (= index 0)
    (cons 'orderless-regexp (concat "^" pattern))))

(defun with-anchored-first-component (fn &rest args)
  (let ((orderless-style-dispatchers
         (cons #'anchor-first-component orderless-style-dispatchers)))
    (apply fn args)))

(advice-add 'company-calculate-candidates
            :around #'with-anchored-first-component)
```

**Comment by oantolin** [comment]
> Any hints for disabling the orderless for some specific regions/hints, say the above one?

I just realized I may not be understanding your question: what do you mean by "specific region/hints"?

**Comment by oantolin** [comment]
Also, I just realized that probably the easiest possible solution here is something like: `(setq completion-styles '(partial-completion orderless))`. That should in practice always use `partial-completion` for `company` while still letting you use `orderless` in the minibuffer.

**Comment by oantolin** [comment]
Please let me know if none of these approaches does what you want, and feel free to reopen the issue.

**Comment by hongyi-zhao** [comment]
> I just realized I may not be understanding your question: what do you mean by "specific region/hints"?

Since I was only faced with a situation that confuses me while using `orderless`, I have no way to describe my needs in general terms. Basically, I want to have a method to let me switch on/off `orderless` on-the-fly. For example, as you mentioned, when a `^` is type as an anchor, enable it, otherwise, disable it.

> Instead of disabling orderless you could alternatively add a style dispatcher that automatically anchors the first component using `^`. If you don't want to use it all the time, you can set things up so that it only is used for company:
 
 ```emacs-lisp
 (use-package orderless
  :config
  (setq
   ;; https://github.com/oantolin/orderless#ivy
   ivy-re-builders-alist '((t . orderless-ivy-re-builder))

   ;; Configure a custom style dispatcher (see the Consult wiki)
   ;; orderless-style-dispatchers '(+orderless-dispatch)
   ;; orderless-component-separator #'orderless-escapable-split-on-space

   completion-styles '(orderless)
   completion-category-defaults nil
   completion-category-overrides '((file (styles . (partial-completion)))))

  (defun anchor-first-component (pattern index _total)
    (when (= index 0)
      (cons 'orderless-regexp (concat "^" pattern))))

  (defun with-anchored-first-component (fn &rest args)
    (let ((orderless-style-dispatchers
           (cons #'anchor-first-component orderless-style-dispatchers)))
      (apply fn args)))

  (advice-add 'company-calculate-candidates
              :around #'with-anchored-first-component)
  )
 ```
It seems that the above configuration will always use `partial-completion` style when I'm not in minibuffer:

![image](https://user-images.githubusercontent.com/11155854/145156192-fc0d7d0f-9622-464c-b2c1-f09f1a01a79b.png)

I mean, without typing `^` an anchor, the `partial-completion` style is always enabled, which prevents me from choosing to use the `orderless` style of completion when necessary.

> `(setq completion-styles '(partial-completion orderless))`

Just as you have mentioned, this configuration can always use `partial-completion` for company while still letting me use `orderless` in the minibuffer. But, as I’ve explained above, it is not flexible enough to allow me to easily switch between using `orderless` and not using `orderless` at any time on-the-fly conveniently.
