### ISSUE TITLE
Escapable split on spaces, hyphen, or slash

### ISSUE THREAD

**Issue by salutis** [oantolin/orderless#102]
I would like to get **both** escaping and splitting on spaces/hyphens/slashes.

When I set `orderless-component-separator` to `'orderless-escapable-split-on-space`, I get splitting on spaces and escaping but not splitting on hyphens and slashes. When I set `orderless-component-separator` to "Spaces, hyphen or slash" (` +\\|[-/]`), I get splitting on spaces/hyphens/slashes but not escaping.

**Comment by minad** [comment]
Did you try writing your own component separator derived from `orderless-escapable-split-on-space` which handles spaces/hyphens/slashes?

**Comment by oantolin** [comment]
I think this is a pretty niche request, so I agree with @minad that the best way to deal with it is to write in your personal configuration a custom separator based on `orderless-escapable-split-on-space`. Let me know if you get stuck adapting the source code of `orderless-escapable-split-on-space` to your needs.

Also, just in case this is an [XY problem](https://xyproblem.info/), why do you want to split on hyphens and slashes?

**Comment by salutis** [comment]
> Also, just in case this is an [XY problem](https://xyproblem.info/), why do you want to split on hyphens and slashes?

It might be! TL;DR Escapable spaces work well in the mini-buffer, but when writing Scheme with Corfu, I would like to split on hyphens. I tried `corfu-quit-at-boundary` but it annoys me how the completion popup lingers around.

**Comment by salutis** [comment]
For anyone reading in the future, I came up with the following solution:

```emacs-lisp
(defun my-orderless-escapable-split-on-space-and-dash (string)
  (orderless-escapable-split-on-space (string-replace "-" " " string)))

(setq orderless-component-separator
      'my-orderless-escapable-split-on-space-and-dash)
```

Now, Orderless splits (escapably) on dashes (_fantastic_ for Lisp) and spaces (_fantastic_ for everything else).  I left out slashes for now.  😄

**Comment by salutis** [comment]
> Now, Orderless splits [...]

Correction:  My original one-liner above has a problem.  While it splits on both dashes and spaces, it does not interpret escaped dashes correctly.  For instance, `C\-d` would not match `C-d`.  I wrote the version below to fix the problem.

```emacs-lisp
(defun my-orderless-escapable-split-on-space-and-dash (string)
  "Split STRING on spaces and dash, which can be escaped with backslash."
  (let ((encode
         (lambda (string)
           (let* ((step-1 (string-replace "\\ " "&space;" string))
                  (step-2 (string-replace "\\-" "&minus;" step-1)))
             step-2)))
        (decode
         (lambda (string)
           (let* ((step-1 (string-replace "&space;" " " string))
                  (step-2 (string-replace "&minus;" "-" step-1)))
             step-2))))
    (let* ((string-encoded (funcall encode string))
           (components-encoded (split-string string-encoded " +\\|-"))
           (components (mapcar decode components-encoded)))
      components)))
```

**Comment by dadinn** [comment]
I am still using `company`, about to migrate over to corfu, so as an intermediate step I wanted to get multi-component searches to work with coma or colon, instead of space (which exits company).

Here is the code:
```elisp
(defcustom orderless-split-char " "
  "Character to be used as component separator by `orderless-escapable-split'.")

(defun orderless-escapable-split (string)
  "Split STRING on `orderless-split-char' characters, which can be escaped with backslash."
  (let* ((encoded-string
          (string-replace (concat "\\" orderless-split-char) (string 0) string))
         (encoded-components
          (split-string encoded-string orderless-split-char)))
    (mapcar (lambda (component)
              (string-replace (string 0) orderless-split-char component))
            encoded-components)))
```

For the examples below I am using flex+regexp styles:
```elisp
(orderless-matching-styles
   '(orderless-flex orderless-regexp))
```

Some examples:
```elisp
;; keeping this on " " is backward compatible with original behaviour
(setq orderless-split-char ":")       ; completes this: #'orderspt:it$:ect-
(setq orderless-split-char ",")       ; completes this: #'orderspt,it$,etc-

;; it works even with backspace!!! :"D
(setq orderless-split-char "\\\\")    ; completes this: #'orderspt\\it$\\ect-
```
