### ISSUE TITLE
Orderless breaks ESS completion in region

### ISSUE THREAD

**Issue by krvpal** [oantolin/orderless#108]
Hi, thanks for this great package. I've completely switched to `vertico + consult + orderless + marginalia` workflow from `ivy + counsel` in Doom Emacs due to the promise of closer integration with native Emacs functionalities.

It has been working great so far except when I need completions in ESS buffers. I use `ess-mode` for R programming and it is fairly common to have text as follows (note the symbol `$` at the end): 
```R
variable_name$
```
After which ESS related `completion-at-point` functions are used.

When not using `orderless` I get full completion candidates to select something like:
```R
variable_name$col_name
``` 

But when using `orderless` it always returns `No matches`. I believe this has to do with the character `$` right before the cursor when completion at point functions are called.

It took me some time to realize `orderless` was causing this issue and I've tried all the [Component matching styles](https://github.com/oantolin/orderless#component-matching-styles) individually to no avail.  Currently, I've advised ESS completion functions to use Ivy instead just for these situations. I'd really love to just use `vertico + consult + orderless` for ESS completions, please help.

**Comment by oantolin** [comment]
I believe this problem is likely to be solved by setting `completion-styles` to `'(orderless basic)` as now recommended in the documentation.
