### ISSUE TITLE
autoload of cl-pushnew is bad/doesn't work

### ISSUE THREAD

**Issue by darkfeline** [oantolin/orderless#11]
The naive autoloading of `cl-pushnew` is bad for a number of reasons:

1. This forces users to load the large `cl-lib` library when packages are initialized.
2. `cl-pushnew` is not an autoloaded macro, so this will cause Emacs to fail to load packages if there is no other package or user config that is loading `cl-lib`.

**Comment by oantolin** [comment]
Oh, I thought `cl-lib` was in such widespead use it was almost unavoidable. I'll replace this with `add-to-list`.

Specifically, I'll do this:

```elisp

;;;###autoload
(with-eval-after-load 'ivy
  (add-to-list 'ivy-highlight-functions-alist
               '(orderless-ivy-re-builder . orderless-ivy-highlight)))
```

Is that better?

**Comment by oantolin** [comment]
I believe this should be working now. Please, let me know if it works on your end so we can close this issue.

**Comment by darkfeline** [comment]
That looks fine, thanks.

**Comment by darkfeline** [comment]
There's another autoloaded `cl-pushnew` by the way.  Also, if you add the URL to the bug in the commit it will get linked here.

**Comment by oantolin** [comment]
> There's another autoloaded cl-pushnew by the way.

Right, thanks! I've fixed it now.

> Also, if you add the URL to the bug in the commit it will get linked here.

Thanks, I'll try to remember that next time.

I'm closing this issue.
