### ISSUE TITLE
orderless doesn't work with fido

### ISSUE THREAD

**Issue by Ice-Cube69** [oantolin/orderless#110]
I tested this plugin with both vertico and fido. It works with vertico as expected, but when i try to use it with fido, fido can't find anything:
![image](https://user-images.githubusercontent.com/47600778/161763918-c9e3613c-dbaa-4ee8-882c-26a875b0ec2b.png)
Weirdly enough, it does work with icomplete though, so it could also be possible that this is a bug with fido.

**Comment by oantolin** [comment]
It's not exactly a bug with fido, it's just that fido is very opinionated: it completely ignores your `completion-styles` setting and uses only the `flex` completion style.

**Comment by oantolin** [comment]
So I think you have two options if you want something fido-like but that lets you use `completion-styles` other than `flex`:

1. Settle for icomplete.

2. Use `fido-mode` and set `completion-styles` *after* fido messes it up. I seem to recall that setting `completion-styles` in a `minibuffer-setup-hook` works.

**Comment by oantolin** [comment]
Yep, this works to enable orderless in fido-mode:

```elisp
(defun use-orderless ()
  (setq completion-styles '(orderless)))

(add-hook 'minibuffer-setup-hook #'use-orderless)
```

**Comment by Ice-Cube69** [comment]
Thanks, it now works! But I think I might move to something else, this is pretty weird.

**Comment by oantolin** [comment]
If you are after the horizontal display of candidates that icomplete and fido use, I recommend using Vertico with the vertico-flat extension.
