### ISSUE TITLE
Release new version 0.8 on GNU ELPA

### ISSUE THREAD

**Issue by skangas** [oantolin/orderless#116]
Please consider releasing a new version 0.8 on GNU ELPA. (I guess it's enough to bump the version header.)

Thanks!

**Comment by minad** [comment]
I would wait a bit (a week or a month). Omar just pushed bigger changes.

**Comment by minad** [comment]
I recommend the following configuration if living on the edge is fine for you.

~~~ elisp 
(setq package-archives '(("gnu-devel" . "https://elpa.gnu.org/devel/")
                         ("nongnu-devel" . "https://elpa.gnu.org/nongnu-devel/")
                         ("melpa-devel" . "https://melpa.org/packages/"))
      package-archive-priorities '(("gnu-devel" . 2)
                                   ("nongnu-devel" . 1)
                                   ("melpa-devel" . 0))
      package-archive-column-width 14
      package-version-column-width 26)
~~~

**Comment by doublep** [comment]
Ping.

**Comment by oantolin** [comment]
Sure, I guess it is time now. Things have stabilized again.

**Comment by doublep** [comment]
FWIW, while 0.8 is now available from GNU ELPA, MELPA Stable still ships 0.7. I guess you need to put a tag on the released version.

**Comment by oantolin** [comment]
Whoops, thanks for reminding me about MELPA Stable.
