### ISSUE TITLE
Completion variables recommended configuration

### ISSUE THREAD

**Issue by Andre0991** [oantolin/orderless#117]
Hi.

I found this [comment](https://github.com/joaotavora/eglot/issues/131) in Eglot issue tracker.

It seems that using `(setq completion-category-overrides)` instead of `add-to-list` was an issue, since that replaced some Eglot configuration.

I haven’t faced this issue, but I’m wondering if it would make sense for orderless to recommend using `add-to-list` in its README.

WDYT?

**Comment by minad** [comment]
`completion-category-overrides` is for user-specific overrides. Eglot should probably rather use `completion-category-defaults`? However this will still leave us with the problem. Orderless recommends to reset these variables to ensure that you get a consistent Orderless UI everywhere. Unfortunately `completion-category-defaults` comes with many presets which are not really necessary and which lead to an inconsistent UI. On Emacs 28:

~~~ elisp
(defvar completion-category-defaults
  '((buffer (styles . (basic substring)))
    (unicode-name (styles . (basic substring)))
    ;; A new style that combines substring and pcm might be better,
    ;; e.g. one that does not anchor to bos.
    (project-file (styles . (substring)))
    (xref-location (styles . (substring)))
    (info-menu (styles . (basic substring)))
    (symbol-help (styles . (basic shorthand substring))))
~~~

We could recommend instead in the README that the user should remove the undesired entries from the list, e.g.,

~~~ elisp
(setq completion-category-defaults
      (assq-delete-all 'buffer completion-category-defaults))
(setq completion-category-defaults
      (assq-delete-all 'unicode-name completion-category-defaults))
...
~~~

At least a warning in the readme would be appropriate.

**Comment by minad** [comment]
The same issue applies to the Corfu and Vertico READMEs. Also some packages modify the `completion-category-defaults` variable afterwards, e.g., message.el adds `(email (styles substring))` which is unnecessary given Orderless. My configuration even contains this:

~~~ elisp
(with-eval-after-load 'message
   (setq completion-category-defaults
           (delete '(email (styles substring))
                   completion-category-defaults)))
~~~

**Comment by Andre0991** [comment]
Indeed, having a consistent experience seems like the best default recommended configuration. Maybe the README could warn users about the caveats. But maybe not. Thanks for the explanation!
