### ISSUE TITLE
How do I dispatch filtering on a suffix?

### ISSUE THREAD

**Issue by benjamin-asdf** [oantolin/orderless#123]
```lisp 
(defun suffix-when-dot-at-end (pattern _index _total)
    (cond
     ((string-suffix-p "." pattern)
      `(orderless-regexp . ,(format "^.+?%s$" (substring pattern 0 -1))))))
```
      
this works:

```lisp 
  (setq orderless-style-dispatchers '(suffix-when-dot-at-end))
  (completing-read "fo: " '("foo.org" "bar.lol"))
```

but somehow my filter removes all cands when I try with `consult-buffer` do you have a clue why that is?

**Comment by minad** [comment]
See https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer and 
https://github.com/minad/consult/wiki#minads-orderless-configuration

**Comment by benjamin-asdf** [comment]
Oh nice that is truly juicy, thanks

**Comment by oantolin** [comment]
Thanks for the links, @minad.
