### ISSUE TITLE
Confusing highlighting when using `orderless-flex` style

### ISSUE THREAD

**Issue by doublep** [oantolin/orderless#127]
To reproduce:

1. Have source code of Emacs somewhere, e.g. in `~/git/emacs`.
2. From command line, from directory with Orderless source code, run as `emacs -Q -L . ~/git/emacs --eval "(progn (require 'orderless) (setf completion-styles '(orderless) orderless-matching-styles '(orderless-flex)))"`, replacing `~/git/emacs` as needed.
3. Type `C-x p f`, then string "XMA" and `TAB` to show the list of matching completions.

I have one last completion highlighted wrongly ("old**XM**enu/XM**a**keAssoc.c"). It does apply matching correctly: there is an uppercase letter "A", but a different "a", in lowercase, is highlighted.

Of course this is only an example, I have it all over the place in a real project (it is Java code, nearly all files have uppercase letters in the name).

Tested with Emacs 28 and 29.

**Comment by oantolin** [comment]
Thanks for reporting! I bet I just forgot to set completion-ignore-case according to orderless-smart-case in the highlighting code.

**Comment by oantolin** [comment]
Yep, that was the problem.

**Comment by doublep** [comment]
> I bet I just forgot

Speaking of which, would you be interested in setting up continuous integration system for the project? This will ensure that you won't forget things for which tests exist after refactoring. As I see there are currently no tests, but I'm willing to write a couple at least. Do you prefer ERT or Buttercup for that?
