### ISSUE TITLE
Orderless with a single component

### ISSUE THREAD

**Issue by salutis** [oantolin/orderless#128]
**Configuration**

`(setq completion-styles '(orderless))`

- a custom `orderless-component-separator` function that splits on unescaped `+`, `-`, and space
- the built-in Emacs 29 completion framework

**Reproduction steps**

  1. `C-h f`
  2. `warning TAB`

**Actual results**

I see the following 3 completions:

- `warning-numeric-level`
- `warning-suppress-p`
- `warnings-suppress`

**Expected results**

I would like to also see _all_ completions that contain the `warning` component, such as `display-warning`.

**Important notes**

When I enter `warning+` instead of `warning`, I _do_ see all candidates that contain the `warning` component (per the expected results), but I often **forget** to type that `+` at the end.  I also tried to mix `orderless` with `substring`, but it did not help.

Any ideas?

**Comment by oantolin** [comment]
My first instinct is that it doesn't sound like orderless is doing the matching here, but some other completion style is getting first crack instead. What values of `completion-category-defaults` and `completion-category-overrides` are you using?

**Comment by salutis** [comment]
> My first instinct is that it doesn't sound like orderless is doing the matching here, but some other completion style is getting first crack instead. What values of `completion-category-defaults` and `completion-category-overrides` are you using?

I set both variables to `nil` and ... magic! ... everything works as expected.  **Thank you** for taking the time to help me, @oantolin!  I will study the documentation to find the best values for the variables.

**Comment by salutis** [comment]
FYI: I cross-posted the answer to `help-gnu-emacs`:

https://lists.gnu.org/archive/html/help-gnu-emacs/2022-11/msg00501.html
