### ISSUE TITLE
Use company, orderless, company-fuzzy, auctex, and ispell all together.

### ISSUE THREAD

**Issue by hongyi-zhao** [oantolin/orderless#138]
I want to obtain the following purpose:

1. For minibuffer completion, using orderless.
2. For normal buffer completion with auctex based LaTeX document preparation, using [company-fuzzy](https://github.com/jcs-elpa/company-fuzzy), ispell, and the self-made [english-wordlist](https://github.com/hongyi-zhao/english-wordlist). 

I'm not sure if this is possible. Currently, I encounter [a problem](https://github.com/jcs-elpa/company-fuzzy/issues/37), which has not been solved yet.

Any hints/comments will be appreciated.

Regards,
Zhao

**Comment by oantolin** [comment]
Did I read that issue you linked correctly? It sounds like you still had the problem even without orderless, no?

**Comment by hongyi-zhao** [comment]
It seems like this, but my ultimate goal is to obtain the maximum convenience from the collaborative work of all these packages.

**Comment by oantolin** [comment]
Sure, but in that case, since this like a problem with company, not orderless, I'm unlikely to be able to help (I don't use company myself).

**Comment by hongyi-zhao** [comment]
Ok, I see and will close this issue.

**Comment by oantolin** [comment]
I installed company and tried the code [suggested here](https://github.com/jcs-elpa/company-fuzzy/issues/37#issuecomment-1497214877) and for me both `iso` and `isoph` give the expected completions, even with orderless configured. So if you don't get the correct results for `isoph` something else is going on. It's weird.

**Comment by hongyi-zhao** [comment]
Could you please give all of your configurations involved in the above testing?
