### ISSUE TITLE
Full matched candidate is often not the first one

### ISSUE THREAD

**Issue by netjune** [oantolin/orderless#144]
Doesn't it support sorting?

**Comment by minad** [comment]
Orderless does not sort. This is intentionally unsupported. But completion UIs like Vertico make sure that the exactly matched candidate comes first.

**Comment by netjune** [comment]
OK. Thanks.

I just set `orderless-matching-styles`  to `'(orderless-literal)`. It seems better now.

**Comment by netjune** [comment]
OK. Thanks.

I just set `orderless-matching-styles`  to `'(orderless-literal)`. It seems better now.
