### ISSUE TITLE
Remove orderless-temporarily-change-separator

### ISSUE THREAD

**Issue by oantolin** [oantolin/orderless#15]
This command is only one of many ways to interactively change the separator. Besides prompting for the new separator, like this command does, you could toggle between two choices, cycle among a list of many, popup a hydra of choices, use the top of the kill-ring or some register, etc. It seems a matter of personal preference.

Probably choosing one particular way of interactively changing the separator and putting it in the package is a bad idea. Specially since I would guess the most popular thing is to not change the separator interactively at all, and people who do change it interactively probably have a fixed set of choices. A better option is to document various methods of interactively changing the separator on the Wiki.

So I've marked this function as obsolete and have created this issue, to have a location for comments on the matter.

**EDIT**: `orderless` now includes a variable called `orderless-transient-component-separator` intended to make writing such commands much easier.

**Comment by noctuid** [comment]
I mentioned this in the other issue, but it's kind of been buried. As an alternative, it might be nice if you could do something like escape spaces to make then not act as separators.

**Comment by oantolin** [comment]
Yes, that might be a good idea. One workaround in the meantime, if you are using regexp matching, is to use `\s-` for the whitespace character category. (That matches whitespace in general, not just spaces.)

**Comment by oantolin** [comment]
How does just using `split-string-and-unquote` instead of `split-string` sound?

This would let you use spaces in a component by surrounding the component in double quotes. And you can still put double quotes in your pattern by putting them in a quoted component and escaping them with backslashes: `a "b c" d "e \"f g"` => `a`, `b c`, `d`, `e "f g`

**Comment by noctuid** [comment]
Ah it's similar shell args. I don't know whether I would want to search for quotes or spaces more often, and this is a little lengthier. Probably it is the simplest solution though. I'd be okay with it.

**Comment by oantolin** [comment]
Oh, @noctuid, `split-string-and-unquote` discard empty components automatically, is that a deal-breaker?

**Comment by noctuid** [comment]
Yeah :/ I guess another approach I could use is transform another character to a space. Or use a different pattern compiler to change the separator.

**Comment by oantolin** [comment]
OK, I've been putting this off long enough. In the latest commit (5c2f44d), the separator can be a function too, and I added an `orderless-escapeable-split-on-space` for you to use, @noctuid
