### ISSUE TITLE
Orderless breaks some functions

### ISSUE THREAD

**Issue by emanresudab** [oantolin/orderless#16]
Hi, I've been using Orderless for a while and I love it, however there have been a few minor annoyances. Specifically, I used to be able to type in `ev-b` for `eval-buffer`, but now, Orderless expands `ev-b` to `switch-to-prev-buffer`. I'm not even sure what type of solution I'm looking for, but is there a completion style I'm not aware of that could help this?

**Comment by oantolin** [comment]
Hi @emanresudab! The short version is that you should try the `orderless-prefixes`  matching style:

```elisp
(setq orderless-component-matching-styles
      '(orderless-regexp orderless-prefixes orderless-initialism))
```

Please let me know if that fixes your problem.

The long version is that before you used `orderless` you were most likely using the `partial-completion` completion style which does indeed let `ev-b` match `eval-buffer`. If you are using `(setq completion-styles '(orderless))` then you are *only* using the `orderless` completion style now, and if additionally you kept the default matching styles for `orderless` then each space-separated component of your input can match as either a regexp or initialism. The `orderless-prefixes` matching style I recommended above is very similar to Emacs's built-in `partial-completion` completion style. There are many matching styles available for `orderless`, I recommend perusing the [README](https://github.com/oantolin/orderless/blob/master/README.org).

**Comment by emanresudab** [comment]
Thank you! I did happen to see the other completion styles, but I was under the impression "ev-b" was an alias and not some sort of pattern-matching.
