### ISSUE TITLE
[Q] How do I use `orderless-style-dispatchers` with `ivy`?

### ISSUE THREAD

**Issue by NightMachinery** [oantolin/orderless#164]
Is it possible?

I tried 
```
(setq ivy-re-builders-alist '((t . orderless-ivy-re-builder)))
```
but it doesn't seem to use `orderless-style-dispatchers`?

**Comment by oantolin** [comment]
That function calls orderless's compiler which does use `orderless-style-dispatchers`. Can you provide a recipe to reproduce the problem?

**Comment by NightMachinery** [comment]
I did some tests:
```
(orderless-ivy-re-builder "!12")
```

```
(defun tmp1 (&rest dummy)
  (list (cons
         ;; "\\(?:\\(?:[^1]\\|1?:[^2]\\)\\)+"
         "\\(?:\\(?:[^1]\\|1\\(?:[^2]\\)\\)+\\)"
         ;; "\\(?:\\(\\`\\)\\(?:[^1]\\|\\'\\|1\\(?:[^2]\\|\\'\\)\\)*\\)"
         t))
  )
(setq ivy-re-builders-alist '((t . tmp1)))
```

These tests show that the regexes don't work with `swiper-isearch`, and the problem isn't exactly with orderless. They do work with `swiper` itself ... Do you have any ideas why?

**Comment by oantolin** [comment]
Sorry, no clue. Back when I was an Ivy user I only ever used swiper. I don't think swiper-isearch existed yet in those days.
