### ISSUE TITLE
dired-narrow integration

### ISSUE THREAD

**Issue by noctuid** [oantolin/orderless#17]
Right now I have this in my config:
```elisp
  (defun dired-narrow--orderless-filter (filter)
    (orderless-filter filter (list (dired-utils-get-filename 'no-dir))))

  (defun dired-narrow-orderless ()
    "Narrow a dired buffer to the files matching an orderless query."
    (interactive)
    (dired-narrow--internal #'dired-narrow--orderless-filter))
```

Maybe it would be better to add a command directly to `dired-narrow` that just uses `completion-styles`. I'll have to look into how `completion-styles` actually works. It doesn't seem like changing it affects `all-completions`.

**Comment by oantolin** [comment]
> It doesn't seem like changing it affects `all-completions`.

That's right, the analogous function that does take into account the current `completion-styles` is called `completion-all-completions`.

```elisp
(defun dired-narrow--with-completion-styles (filter)
  (completion-all-completions
   filter
   (list (dired-utils-get-filename 'no-dir))))
```

For this particular function you could also use `completion-try-completion`.

**Comment by noctuid** [comment]
Awesome thanks. I'll make a PR to dired-narrow. Right now I'm trying to make orderless ubiquitous in my workflow (mainly still trying to get it working well with swiper). I'm even testing using it how one would use a generic fuzzy finder like fzf. It looks like even piping 10k lines to emacsclient is pretty instant. Might also be nice to use with something like [emacs-piper](https://gitlab.com/howardabrams/emacs-piper) if it had live filtering.

**Comment by oantolin** [comment]
> I'm even testing using it how one would use a generic fuzzy finder like fzf. It looks like even piping 10k lines to emacsclient is pretty instant.

That's amazing!
