### ISSUE TITLE
New release 1.1?

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#171]
Hi Omar,

shall we tag a new release 1.1? I think the newly added functionality is sufficiently solid now.

**Comment by oantolin** [comment]
Yep, sounds great. Will you do the honors, it's your functionality after all?

**Comment by minad** [comment]
Okay, I will do. Is it okay if I add myself to the Maintainer package header such that I receive ELPA-related mails too?

**Comment by oantolin** [comment]
Oh, absolutely, please add yourself.

**Comment by minad** [comment]
Done in https://github.com/oantolin/orderless/commit/3847f311077efa17951a786d2759f2639c5f43c8
