### ISSUE TITLE
Is it possible to include spaces in orderless-literal?

### ISSUE THREAD

**Issue by arozbiz** [oantolin/orderless#173]
Sometimes I would like to enter a multi word string and have orderless treat the entire string as a literal, rather than have it break it into components at the spaces. One (clunky) way of doing this is using regex:  `first[[:space:]]second[[:space:]]third`. But ideally I could write something like `='first second third'` instead. Is something like this possible?

**Comment by oantolin** [comment]
If you are using the escapeable space splitter (which recently made the default) you can use backslash to escape a space

**Comment by arozbiz** [comment]
Brilliant, thank you!
