### ISSUE TITLE
Search annotations by default

### ISSUE THREAD

**Issue by vermiculus** [oantolin/orderless#180]
I may be thinking about this the wrong way, so I'll first describe what I'm trying to do.

I've got a list of alphanumeric bug IDs where I can get the bug title easily, creating (for example) a data structure like this:

```lisp
(("123" . "Bug one hundred twenty-three")
 ("456" . "Ladybugs have invaded the house"))
```

The bug ID isn't memorable (and in real life, it's pretty long – we're up to seven digits now), so I'd like to complete on either the bug ID or the bug title – but get only the bug ID out of `completing-read`. When passed an alist like this, however, `completing-read` only displays/searches each `car` (as described in the manual).

---

I can define an annotation function that also prints this title, so I can get a completion list that looks like

```
123    Bug one hundred twenty-three
456    Ladybugs have invaded the house
```

and then I can match on 456 with `&invaded`. Entering a candidate string like `&this &all &the &time` would get pretty annoying, though, and isn't at all clear to a user of my package why it would have to be that way. (It also rather assumes they're using orderless, which isn't ideal, but 🤷)

What's the right way to do this? If this a reasonable approach (which I somewhat doubt), is there a means by which those `&` modifiers could be inserted by default without a brute-force approach like modifying the minibuffer keymap?

Thanks :-)

**Comment by oantolin** [comment]
Any text you want the user to be able to see and yo match on independently of what completion styles and completion UI they use should be made part of the candidate text. So make the candidate "123    Bug one hundred twenty-three" be and you can extract the number afterwards.

**Comment by oantolin** [comment]
I would say putting something only in the annotation and not in the candidate text is how you single that while users may want to see it, they are not going to want toa match on it.

**Comment by vermiculus** [comment]
Is there no standard pattern for wanting to select an element of some complex data structure using a representative (but not necessarily unique) property of each element? For example, in the event I didn't want to show the bug ID but two bugs had the same title?

Or is that getting into the territory of 'things that don't really make sense when talking about `completing-read`'?

**Comment by oantolin** [comment]
As far as I know the usual way of handling that is too create unique strings for each candidate, call completing-read on those and then lookup the object corresponding to the string. You can make an almost for examples mapping the uniquefied user-readable strings to objects, call completing-read on the a list and lookup the result in the alist. I think that's the most idiomatic way. It's certainly what consult does, for example.

**Comment by oantolin** [comment]
Bear in my mind that user will need to be able to tell which option to choose from just looking at the candidate string (or maybe candidate+ annotation if you want to force the user to use a completion UI that displays annotations). So you definitely need to make these string unique anyway.
