### ISSUE TITLE
How can I use the orderless framework while preserving ordered matching of components

### ISSUE THREAD

**Issue by jsyjr** [oantolin/orderless#182]
The vast majority of my completion attempts involve targeting a symbol / identifier / ... that I already know, and whose abbreviated components I enter in left-to-right order.  In such cases, matching components "orderlessly" produces false positives, often forcing me to restart the completion or, at the very least, making me choose from the candidates.

Is it possible to use the orderless framework while insisting on strict left-to-right matching?

**Comment by meedstrom** [comment]
How's it going for you? I made a similar issue: #187

**Comment by oantolin** [comment]
Try the orderless-prefixes matching style for symbols, or the orderless-flex matching style.
