### ISSUE TITLE
Can you make a release for 1.3?

### ISSUE THREAD

**Issue by hapst3r** [oantolin/orderless#183]
Hej fellows,

as the title says, I wanted to ask if you could make a release for 1.3. This would simplify the update process for the Guix package recipe for orderless.

In case this is too much work, I understand that commit `2b7a1688f24cc8ef5a3c3a6dab8e00d833bcda59` is the commit equivalent of a 1.3 release?

Merry Christmas, have a good time, fellows :)

**Comment by minad** [comment]
Done. I wonder how it makes a difference if a release is made on Github. In my projects (Consult, Vertico, etc) I only add tags to the release commits.

**Comment by hapst3r** [comment]
You're correct, a tag works as well. Thanks!

**Comment by oantolin** [comment]
Thanks for handling this, @minad.
