### ISSUE TITLE
camelCase initialism matching

### ISSUE THREAD

**Issue by noctuid** [oantolin/orderless#19]
Is there some easy way to achieve this globally currently? I thought `(global-)subword-mode` might do the trick, but it doesn't look like it.

**Comment by oantolin** [comment]
I think those modes only alter word motions commands, not the meaning of regexps.

Probably matching camelCase initialisms is best done by writing a new component matching style.

**Comment by oantolin** [comment]
I think writing a new component matching style is the best way to go here. If anyone wants to contribute one to the wiki that would be great. (I don't think there is enough demand for this matching styles to go into orderless itself, but if that changes we can certainly consider including it.)
