### ISSUE TITLE
Breaks `icomplete-vertical' resize and obscures candidates

### ISSUE THREAD

**Issue by protesilaos** [oantolin/orderless#2]
Thank you for publishing this!

When given a list of candidates:

![Screenshot at 2020-04-14 06-48-43](https://user-images.githubusercontent.com/12828033/79184476-e981bf80-7e1c-11ea-8dc2-558f85d1c346.png)

A failed match will not shrink the minibuffer (as per `resize-mini-windows t`):

![Screenshot at 2020-04-14 06-48-53](https://user-images.githubusercontent.com/12828033/79184541-18983100-7e1d-11ea-937f-4f1b6b289e22.png)

The above also throws: `Error in post-command-hook (icomplete-post-command-hook): (wrong-type-argument listp 0)`

From that point, deleting the mismatching input and hitting SPC will automatically expand the first match, as if that were the only one:

![Screenshot at 2020-04-14 06-50-26](https://user-images.githubusercontent.com/12828033/79184613-54cb9180-7e1d-11ea-9e7c-df43b1ee4505.png)

But from that point, hitting TAB (`minibuffer-complete`) will actually cycle through the candidates even though they are not visible.

Using your [icomplete-vertical](https://github.com/oantolin/icomplete-vertical), though all of the above except minibuffer-resizing apply to the horizontal layout.

**Comment by protesilaos** [comment]
UPDATE: the note about SPC completing the first match is due to this not actually removing the command:

```elisp
(define-key minibuffer-local-map (kbd "SPC") nil)
```

Had to use:

```elisp
(define-key icomplete-minibuffer-map (kbd "SPC") nil)
```

With that in place, the behaviour of completing the first candidate is no longer present, though all the rest do persist.

**Comment by oantolin** [comment]
Try it now, I think I fixed the bug with no matches.

I'm a little surprised about SPC being bound in icomplete-minibuffer-map, I don't seem to have it bound there. Maybe it's because we're on different Emacs versions?

**Comment by protesilaos** [comment]
Okay, I will check.

With regard to the keymap I am on Emacs 27.0.90. I think something has to do with `icomplete-mode`. I even tried it in `emacs -Q`:

```elisp
;; Works on its own
(define-key minibuffer-local-map (kbd "SPC") nil)

;; Defaults to `minibuffer-complete-word'
(icomplete-mode 1)
```

Even if I disable the mode and evaluate the key again, it still gives me `minibuffer-complete-word`.

At any rate, your latest commit seems to have fixed this issue.

**Comment by oantolin** [comment]
Oh! I made a typo, sorry! It should say:

```elisp
(define-key minibuffer-local-completion-map (kbc "SPC") nil)
```
I missed the word "completion". I'll go update the README.

> At any rate, your latest commit seems to have fixed this issue.

You mean the errors and disappearing candidates? The fixed worked in your testing too?

**Comment by protesilaos** [comment]
Yes, the errors can no longer be reproduced.

**Comment by oantolin** [comment]
Excellent, I'm closing this issue then. Thanks for reporting! [Now I'll go take a look at the other issues you filed. :)]

**Comment by protesilaos** [comment]
Great!

**Comment by protesilaos** [comment]
By the way, this patch concerns the key map you fixed earlier. I can do the pull request thing if you want, but am okay either way.

```diff
 orderless.el | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/orderless.el b/orderless.el
index c515056..6290e26 100644
--- a/orderless.el
+++ b/orderless.el
@@ -35,13 +35,13 @@
 ;; documentation.
 ;;
 ;; By default the space key is bound to `minibuffer-complete-word' in
-;; `minibuffer-local-map', which isn't useful with this completion
-;; method. So, if you use it, you should also unbind SPC.
+;; `minibuffer-local-completion-map', which isn't useful with this
+;; completion method. So, if you use it, you should also unbind SPC.
 ;;
 ;; So to test this completion you can use the following configuration:
 ;;
 ;; (setq completion-styles '(orderless))
-;; (define-key minibuffer-local-map (kbd "SPC") #'self-insert-command)
+;; (define-key minibuffer-local-completion-map (kbd "SPC") #'self-insert-command)
 
 ;;; Code:
 ```
