### ISSUE TITLE
orderless & company-capf

### ISSUE THREAD

**Issue by tpeacock19** [oantolin/orderless#23]
I'm not quite sure how to debug this but I figured I should at least post it. Whenever my emacs instance has been running for some time the performance of `company-capf` degrades to a standstill. I've done a profile when running some completion in an empty buffer and I got the below. Indicating something in `orderless-filter`. However, even if I enable edebug on this function I cannot seem to trigger it to determine the issue. Have you experienced anything similar?

```
- company-post-command                                           1451  85%
 - company--perform                                              1441  84%
  - company--continue                                            1439  84%
   - company-calculate-candidates                                1439  84%
    - company--fetch-candidates                                  1427  83%
     - company-call-backend-raw                                  1427  83%
      - apply                                                    1427  83%
       - company-capf                                            1427  83%
        - company-capf--candidates                               1427  83%
         - completion-all-completions                            1427  83%
          - completion--nth-completion                           1427  83%
           - completion--some                                    1427  83%
            - #<compiled 0x808f96f84b95aa8>                      1427  83%
             - orderless-all-completions                         1427  83%
              - orderless-filter                                 1410  82%
               - condition-case                                  1410  82%
                - save-match-data                                1410  82%
                 - let                                           1410  82%
                  - unwind-protect                               1410  82%
                   - progn                                       1410  82%
                    - pcase-let*                                 1410  82%
                     - let*                                      1410  82%
                      - let                                      1410  82%
                         let*                                    1410  82%
              + orderless-highlight-matches                        16   0%
    + company--postprocess-candidates                               9   0%
  + company-call-frontends                                          2   0%
 + company-call-frontends                                          10   0%
+ command-execute                                                  93   5%
+ ...                                                              67   3%
+ redisplay_internal (C function)                                  53   3%
+ timer-event-handler                                              33   1%
+ server-process-filter                                             6   0%
```

This is the profile when the same completion is run with `completion-styles = '(basic partial-completion)`

```
- command-execute                                                 755  55%
 + funcall-interactively                                          755  55%
- company-post-command                                            324  23%
 - company--perform                                               282  20%
  - company--continue                                             274  19%
   - company-calculate-candidates                                 271  19%
    - company--fetch-candidates                                   270  19%
     - company-call-backend-raw                                   270  19%
      - apply                                                     270  19%
       - company-capf                                             270  19%
        - company-capf--candidates                                270  19%
         - completion-all-completions                             270  19%
          - completion--nth-completion                            270  19%
           - completion--some                                     270  19%
            - #<compiled 0x808f7f942f944a8>                       270  19%
               completion-basic-all-completions                   258  18%
             - completion-pcm-all-completions                      12   0%
                completion-pcm--find-all-completions                 12   0%
   + company-call-backend                                           1   0%
     company-update-candidates                                      1   0%
   + company-cancel                                                 1   0%
  + company-call-frontends                                          8   0%
 + company-call-frontends                                          42   3%
+ timer-event-handler                                             142  10%
+ redisplay_internal (C function)                                 108   7%
+ ...                                                              30   2%
+ server-process-filter                                             7   0%
  posframe-run-hidehandler                                          1   0%
+ flycheck-maybe-display-error-at-point-soon                        1   0%
+ evil-repeat-post-hook                                             1   0%
  amx-save-to-file                                                  1   0%
+ highlight-parentheses--initiate-highlight                         1   0%
```

**Comment by terlar** [comment]
I didn't manage to get completions work with `company`, all the candidates, includes whatever I wrote + the garbled matches.
![Screenshot from 2021-01-04 18-01-47](https://user-images.githubusercontent.com/280235/103559762-f4064c80-4eb6-11eb-9a5a-9fc94a8b3d7d.png)

Accepting candidate 9, results in `(usepkguse-package)`

**Comment by oantolin** [comment]
I don't use company myself, but I'll try to install it when I get the chance and see if I can figure this out. I remember testing it a while ago when I wrote the section of the Readme on company, and I think it did work back then.

**Comment by oantolin** [comment]
I can't reproduce this bug, @terlar. I installed company, turned on `company-mode`, set `company-show-numbers` to `t`, and tried using company in the `*scratch*` buffer. It worked fine, the completion did delete my initial input. Then I tried turning off my orderless config and using yours, and it still worked fine. Then I tried from `emacs -q`, loading only company and orderless, and it still worked.

I'd love to help you out, but it's practically impossible without knowing how to trigger the error. I suggest you use the fantastic [bug-hunter](https://elpa.gnu.org/packages/bug-hunter.html) with the interactive option to figure out what part of your init file is relevant to this bug.

**Comment by oantolin** [comment]
Well, the resolution of bug-hunter is an s-expression I believe. So if you use `use-package` you'll probably have to bisect your `company` config by hand.

**Comment by terlar** [comment]
Indeed! Running with `emacs -Q` this didn't occur. Really curious what part is causing this, because I don't configure `company` much. So most be some interference of some other package/settings...

So I did some further investigation and lo and behold and it turns out it was my config. Here is a minimal reproduction via `emacs -Q`

```emacs-lisp
(require 'orderless)
(require 'company)
(setq completion-styles '(orderless))
(setq orderless-matching-styles '(orderless-regexp orderless-flex))
(require 'use-package)
(setq company-backends
        '((company-files
           company-keywords
           company-capf
           company-dabbrev-code
           company-dabbrev)))
(emacs-lisp-mode 1)
(company-mode 1)
```

Enter `usepkg`

Then it should look like this:
![Screenshot from 2021-01-12 23-09-32](https://user-images.githubusercontent.com/280235/104380483-5997b000-552b-11eb-97ba-640b8831e13d.png)

**Comment by oantolin** [comment]
Oh, that's weird. And it's starting to sound like a company bug, not an orderless bug.

**Comment by terlar** [comment]
It seems to only when `company-dabbrev` is on the list, if I remove that it works. Indeed, but without `orderless` this behavior doesn't occur. I have also tried the `company-fuzzy` (which also fuzzy matches) library and that also works without issues.

So unless I can find a way to reproduce this without `orderless`, I am not entirely convinced, although  it seems like it, but I also have no insight into the implementation of orderless if this could even be possible.

**Comment by terlar** [comment]
Even smaller repro:
```
(setq company-backends '((company-capf company-dabbrev)))
```

**Comment by terlar** [comment]
If you insist I will open a ticket with `company` instead.

**Comment by oantolin** [comment]
I'm not insisting yet. Let me try `(setq company-backends '((company-capf company-dabbrev)))` and see if I can figure it out.

**Comment by oantolin** [comment]
OK, *now* I insist you file a bug report with company. 😄

I could reproduce the problem without orderless:

```elisp
(setq company-backends '((company-capf company-dabbrev)))
(setq completion-styles '(partial-completion))
```

**Comment by terlar** [comment]
Thank you, did I steal this issue? The title applies, but I guess this was a different problem than @tpeacock19 had. So not sure if it should be closed.

**Comment by oantolin** [comment]
That's right! Sorry, @tpeacock19.

**Comment by tpeacock19** [comment]
No problem, This was a bit ago but I remember identifying that this only occurred in `emacs-lisp-mode` and subsequently removing `company-capf` from the backends when working in elisp. Further, I cant replicate it today even if I reintroduce `company-capf` so I think its fine to close this out.

**Comment by oantolin** [comment]
I'm glad it seems to longer happen.
