### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#25]
@oantolin I must say, I really like this package. I just added the twiddle flex matching to my init.el. It is really nice how this thing can be tweaked. In particular I like that this package is so easy to integrate - only replace the completion-style and done.

Right now I am using orderless without any fancy sorting package, but it would probably be nice to use something based on frecency. There is prescient and then there is the frecency package on melpa (but I think this is only the algorithm). What do you use?

**Comment by oantolin** [comment]
I actually don't use any sorting at all. Never felt the need for it. For a while I use icomplete which puts recent candidates at the top. When I started using `(setq completing-read-function #'embark-completing-read)` I didn't miss the sorting, so I never did anything about it.

**Comment by minad** [comment]
Ok, thanks! I will probably try prescient at some point but I would like it more if it would only do sorting.

**Comment by clemera** [comment]
I use prescient only for sorting and orderless for filtering and highlighting.

**Comment by minad** [comment]
@clemera I didn't understand yet how the setup works. The prescient-selectrum package does a lot of overwriting and also sets the filtering.

**Comment by clemera** [comment]
I use the following:

```elisp
(prescient-persist-mode 1)
(selectrum-prescient-mode 1)
(setq selectrum-refine-candidates-function #'orderless-filter)
(setq selectrum-highlight-candidates-function #'orderless-highlight-matches)
```

**Comment by minad** [comment]
Ok, simple enough! I will try this!

**Comment by oantolin** [comment]
A little off-topic, but here because you mentioned orderless's highlighting: I think we went overboard with the entire configuration system in orderless, @clemera, adding a bunch of ways of configuring before we had experience indicating we really would use them, and I thought we only really needed `orderless-pattern-compiler`. So I wrote the much smaller [regexpecto](https://github.com/oantolin/emacs-config/blob/master/my-lisp/regexpect.el) by copy/pasting from orderless, and used it for a while. Eventually I went back to orderless because of the pretty colors!

**Comment by minad** [comment]
@oantolin What about cutting out the unnecessary parts from orderless now? If I understood correctly - there is some stuff which could go without loss of functionality?

**Comment by clemera** [comment]
I would be okay with that, I was pretty excited about the possibilities back then but I have to admit I don't use them extensively...

**Comment by oantolin** [comment]
Depends on what you mean by "without loss of functionality", if you mean "if we remove this, people can rewrite their config to using the remaining bits of orderless", then you can remove all the matching styles and the support for style dispatchers and leave only `orderless-pattern-compiler`. But if people do use those features they'd have plenty of rewriting to do.

That would be the most extreme removal. I wouldn't seriously propose that. I think matching styles are very convenient and I would guess most people use them (even if I out of laziness I don't: when I returned to orderless I was too lazy to rewrite my `regexpect` config to use the matching styles that come with orderless, so I just set `orderless-matching-styles` to my regexpect pattern compiler 😆).  I might suggest removing the whole style dispatchers system and maybe the transient variables as well.

**Comment by noctuid** [comment]
>  I might suggest removing the whole style dispatchers system

My vote would still be to keep it. I've found it quite useful and would prefer not to rewrite my config.

**Comment by oantolin** [comment]
I love not changing code, @noctuid, so if you want the dispatchers to stay, they'll stay. 😃

Maybe the transient variables should be removed, in favor of the `(minibuffer-with-setup-hook (lambda () (setq-local ...)))` trick.

**Comment by minad** [comment]
The transient variables are already removed (I think I proposed removing them in favor of setq-local). 

The style dispatcher should stay. Everyone likes them since they give you a bit of freedom to tweak the parsing :)

What I would suggest to remove instead is the pattern-compiler variable, which just points to the default compiler. I don't think there are other compilers and if there are you can always use an advice. I don't think such over-generalization/indirection is useful.

**Comment by oantolin** [comment]
Sure, I could remove the pattern compiler variable. I did use it for a long time but finally ported my configuration to the default pattern compiler and a bunch of style dispatchers.

That variable is really only there because it came first. (Of course, it is actually the only configuration necessary –lambda, the ultimate configuration system!— but people seem to like the less flexible matching styles and dispatchers system 😛).

**Comment by minad** [comment]
> That variable is really only there because it came first. (Of course, it is actually the only configuration necessary –lambda, the ultimate configuration system!— but people seem to like the less flexible matching styles and dispatchers system stuck_out_tongue).

Okay that's too complicated for us ;) I think the style dispatcher is a neat compromise. Is there something where you would want an extra compiler?

**Comment by oantolin** [comment]
> Is there something where you would want an extra compiler?

No, I think it can be removed and no-one would miss it at all.
