### ISSUE TITLE
orderless negative matching style

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#26]
You have this ! matcher in your config. Would it be possible to add sth like this to orderless by default? Basically a not-matching style. Right now I am using a simple dispatcher which dispatches based on suffix ~ to flex and to literal with =.

**Comment by oantolin** [comment]
I was lazy in my config and only implemented negative *literals*, would that be good enough? I can certainly add that to orderless.

**Comment by minad** [comment]
@oantolin A negative-literal/not-literal style would be sufficient for me, I am sure. I could also copy your config to my init.el, but I would prefer to keep it a bit simpler. I am using the default regexp+initialism, since flex matches too much for my taste.

I am using this simple dispatcher right now:

~~~ elisp
  (defun config--orderless-dispatch (pattern _index _total)
    (cond
     ((string-suffix-p "!" pattern) `(orderless-negative-literal . ,(substring pattern 0 -1))) ;; NEW ADDITION :)
     ((string-suffix-p "=" pattern) `(orderless-literal . ,(substring pattern 0 -1)))
     ((string-suffix-p "~" pattern) `(orderless-flex . ,(substring pattern 0 -1)))))
~~~

**Comment by oantolin** [comment]
Out of curiosity I just checked what regexp is produced to match string not containing `hello`:

```
\(?:\(\`\)\(?:[^h]\|\'\|h\(?:[^e]\|\'\)\|he\(?:[^l]\|\'\)\|hel\(?:[^l]\|\'\)\|hell\(?:[^o]\|\'\)\)*\'\)
```

It definitely saves a lot of work. I'll put it in.

**Comment by oantolin** [comment]
I called it `orderless-without-literal` instead of `orderless-negative-literal`.

**Comment by minad** [comment]
Great! Thank you very much!
