### ISSUE TITLE
Filtering via matching against metadata-strings/programmable predicates

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#30]
These are just some ideas for discussion, no real feature request.

I wonder if we could have a possibility to filter based on metadata attached to candidates? Candidates could have a property `'candidate-metadata` which could then be matched on using some special syntax. The downside is that this would introduce a heavy implicit dependency on the metadata format. 

Alternatively I can experiment with some consult internal completion style similar to `consult--async-split` and add a consult-specific metadata filtering syntax. Maybe the only command where this is useful is `consult-buffer`? But one could also see it as some in-band generalization of the current Consult narrowing.

Another question is if it is possible to add metadata filtering capabilities to existing commands. For example `describe-variable` could have a special filter "type:c" to show only custom variables. But I have no idea what the best way is to add such special filtering expressions to given commands. I probably would not like to see too much special casing in orderless. Maybe something could be done based on the completion category?

cc @clemera

**Comment by clemera** [comment]
These are interesting ideas, I also see some use cases for special filter expressions based on completion category. For example one could maybe use @match to filter for a match in the docstrings in command/function completions or for example to filter buffer completions for buffers which contain a match for this in their contents (I believe helm also supports this).

**Comment by minad** [comment]
Okay, @clemera your idea is even more interesting. The way I originally thought about this is that consult attaches some metadata to the candidates, but this is obviously not a good idea. But from your idea this gets me thinking how we can implement it nicely.

Add support only to orderless - add a list of `(category key function)` entries, for example `(symbol ?@ (lambda (cand) ...))`. Then these filter functions can be configured afterwards. Only support for consult-multi dispatching would be nice to have!

**Comment by oantolin** [comment]
Ooh, I like that idea!

**Comment by minad** [comment]
I quickly looked into this and it seems to require an additional filtering step since as of now everything is compiled to regular expressions. In `orderless-filter`, does it make sense to use a modified predicate or just walk over the candidates again as returned by `all-completions`?

**Comment by oantolin** [comment]
Here's a different idea: what if we instead have an alist of `(category . extradata)` pairs, where the `extradata` is a function that given a candidate produces either a string or a buffer. Then orderless components that start with a `@` match against the extra string or buffer rather than against the candidate.

This would be nice for matching against buffer contents or docstrings.

**Comment by oantolin** [comment]
Mmh. In both versions we want to select the metadata based on the category, but we already tried that and you conviced me @minad, that [completion styles aren't supposed to know the category](https://github.com/oantolin/orderless/issues/33#issuecomment-763599533).

**Comment by oantolin** [comment]
And anyway maybe both things would be useful: having an extra string to match against, with normal `orderless` matching (I know @protesilaos has wanted the abilitity to match against the annotation), and also arbitrary predicates that are not string matching.

**Comment by minad** [comment]
> Here's a different idea: what if we instead have an alist of (category . extradata) pairs, where the extradata is a function that given a candidate produces either a string or a buffer.

This sounds good too, but what if I want multiple different extradatas? For this I proposed the key. For example I would want to match buffer content and buffer major mode.

> Mmh. In both versions we want to select the metadata based on the category, but we already tried that and you conviced me @minad, that completion styles aren't supposed to know the category.

Ouch, right. But the issue can easily be avoided by the same approach as before - simply define derived completion styles for each category. 

> And anyway maybe both things would be useful: having an extra string to match against, with normal orderless matching (I know @protesilaos has wanted the abilitity to match against the annotation), and also arbitrary predicates that are not string matching.

Yes, both would be even better if it can be implemented with reasonable effort.

**Comment by oantolin** [comment]
I like how you keep the title up to date. 😛

**Comment by oantolin** [comment]
You know, if we keep at it we will eventually match the capabilities Icicles has had for 15 years (or more?) now...

**Comment by minad** [comment]
Yes, that's the plan! Have you tried it?

**Comment by clemera** [comment]
> Ouch, right. But the issue can easily be avoided by the same approach as before - simply define derived completion styles for each category.

I don't really understand what that means? Usually checking for the category isn't a problem but I remember there was a problem with the preview feature as it does run outside the minibuffer right?

**Comment by minad** [comment]
> I don't really understand what that means? Usually checking for the category isn't a problem but I remember there was a problem with the preview feature as it does run outside the minibuffer right?

The completion style is not allowed to access the current completion category. This means we cannot dispatch within the completion style based on the completion category. The solution to this problem is to define multiple completion styles which are then dispatched to based on the category, e.g. orderless-file, orderless-buffer etc. The completion style is then registered in completion-category-overrides/defaults and selected from there.

**Comment by clemera** [comment]
I think "it is not allowed" puts it a bit strongly, this is Emacs ;) Usually it would be reasonable to assume that you can check for it even though it isn't part of the interface. But I agree that it isn't technically correct and it is safer and robust to use the approach you suggested, so all good :) Thanks for the explanation!

**Comment by oantolin** [comment]
Another option is to not dispatch here on anything. There could be a single `orderless-extra-data` variable pointing to a function, and callers of `completing-read` could just `let`-bind or `setq-local` it to the appropriate thing

We could allow the `orderless-extra-data` function to return a string or buffer to match against, or to return a predicate that can do whatever it wants.

Maybe we should treat matching against strings and buffers specially, and have separate `orderless-extra-text` and `orderless-extra-predicate` variables.

(All of these names are placeholders, I'd think more about good names before using these.)

**Comment by clemera** [comment]
Okay and one could then add a function to `minibuffer-setup-hook` which could automatically sets this orderless variable according to the current completion-style.

**Comment by protesilaos** [comment]
> oantolin: And anyway maybe both things would be useful: having an extra string to match against, with normal orderless matching (I know @protesilaos has wanted the abilitity to match against the annotation), and also arbitrary predicates that are not string matching.

This is great!  I am afraid I cannot be of any help here with regard to the technicalities, though I am eager to test any such functionality and provide feedback.

In the meantime, I flush lines in Embark collect buffers (e.g. targeting the `c` meta datum (commands) in `consult-imenu`).

> oantolin: You know, if we keep at it we will eventually match the capabilities Icicles has had for 15 years (or more?) now...

Correct!

> minad: Yes, that's the plan! Have you tried it?
>
> Edit: Here is the list of features we should implement:

Looking forward to the new iceberg package!  Seriously though, there probably are lots of good idea in there.  Drew has intimate knowledge of core Emacs stuff and is a veteran in the field.

**Comment by minad** [comment]
The bundle of these packages is called iceberg from now on :rofl:

**Comment by minad** [comment]
@oantolin 

> Another option is to not dispatch here on anything. There could be a single orderless-extra-data variable pointing to a function, and callers of completing-read could just let-bind or setq-local it to the appropriate thing

Oh, no. Let's not do that. This way we introduce again a coupling. I want this feature to work for existing commands. It should work as well for consult-buffer as for switch-to-buffer etc.

**Comment by clemera** [comment]
@minad If you let users add a function to their setup hook which sets this variable based on the category it would still work automatically.

**Comment by minad** [comment]
Okay as long as we keep everything decoupled and add the metadata matching after the fact for existing commands I am fine with it. You propose that the user should sets a global minibuffer-setup-hook?

**Comment by clemera** [comment]
That is the idea, but using `completion-category-overrides` also sounds like a viable approach to me.

**Comment by minad** [comment]
I wonder if some predefined matchers should be supplied then, similar to how Embark and Marginalia define their additions for the categories - as part of orderless or as part of another package?

**Comment by minad** [comment]
See https://github.com/minad/consult/pull/200, where @juliocc proposed a custom consult-buffer source for showing a subset of buffers. I assume for such use cases it would also be very valuable to have the filtering of buffer sets on the level of orderless via a predicate as discussed in this PR.

**Comment by minad** [comment]
I played a bit around with how such a feature should be implemented and I came to the conclusion that metadata filtering is out of scope for Orderless. Orderless is such a well-written and narrowly focused package, it should keep it focus.

Here is a small prototype - maybe I should package that up at some point. But I am not yet entirely sure if I would actually want to use it. The feature to search through documentations has come up a few times in the context of Marginalia. And in combination with Embark completion is power up to a full file/buffer manager.

~~~ elisp
;; -*- lexical-binding: t -*-
;; completion query

(defun cq-buffer-content (x y)
  (or (string-blank-p y)
    (when-let (buf (get-buffer x))
      (with-current-buffer buf
        (save-excursion
          (save-restriction
            (widen)
            (goto-char (point-min))
            (ignore-errors (search-forward-regexp y nil 'noerror))))))))

(defun cq-buffer-mode (x y)
  (or (string-blank-p y)
    (when-let (buf (get-buffer x))
      (string-match-p y (symbol-name (buffer-local-value 'major-mode buf))))))

(defun cq-documentation (x y)
  (or (string-blank-p y)
    (ignore-errors (string-match-p y (documentation (intern-soft x))))))

(defvar cq-queries
  '((buffer (mode . cq-buffer-mode)
            (content . cq-buffer-content)
            (?* . cq-buffer-mode)
            (?@ . cq-buffer-content))
    (command (doc . cq-documentation)
             (key . cq-command-key)
             (on . cq-mode-on)
             (off . cq-mode-on))))

(defun cq-mode-on (x _)
  (when-let (sym (intern-soft x))
    (and (boundp sym) (memq sym minor-mode-list)  (symbol-value sym))))

(defun cq-mode-off (x _)
  (when-let (sym (intern-soft x))
    (and (boundp sym) (memq sym minor-mode-list)  (not (symbol-value sym)))))

(defun cq-command-key (x _)
  (when-let (sym (intern-soft x))
    (and (fboundp sym) (where-is-internal sym))))

(defun cq-completion-all-completions (orig str table pred _point &optional metadata)
  (let ((filter))
    (setq str
          (replace-regexp-in-string "@[^ ]*" (lambda (x)
                                               (setq x (substring x 1))
                                               (unless (string-blank-p x)
                                                 (push x filter))
                                               "")
                                    str))
    ;; TODO correct point computation
    (when-let* ((result (funcall orig str table pred (length str) metadata))
                (cat (completion-metadata-get metadata 'category)))
      (when-let (queries (and filter
                              (or (alist-get cat cq-queries)
                                  (and (eq cat 'consult-multi)
                                       (apply #'append (mapcar #'cdr cq-queries))))))
        (let* ((last (last result))
               (base (cdr last)))
          (setcdr last nil)
          (setq result (seq-filter (lambda (x)
                                     (when (eq cat 'consult-multi)
                                       (setq x (cdr (get-text-property 0 'consult-multi x))))
                                     (not (seq-find
                                           (lambda (f)
                                             (or
                                              (when-let* ((pos (or (string-match-p "=" f) (length f)))
                                                          (key (intern-soft (substring f 0 pos)))
                                                          (fun (alist-get key queries)))
                                                (not (funcall fun x (if (< pos (length f)) (substring f (1+ pos)) ""))))
                                              (when-let (fun (alist-get (aref f 0) queries))
                                                (not (funcall fun x (substring f 1))))))
                                           filter)))
                                   result))
          (when result
            (setq result (nconc result base)))))
        result)))

(advice-add #'completion-all-completions :around #'cq-completion-all-completions)
~~~
