### ISSUE TITLE
Performance regression due to accessing completion-category-overrides

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#33]
Since d1c0cbf87ba7d927ec64c161ec3aac65b9643b61, there seems to be a major performance regression of the pattern compiler. When running `consult-line`, entering a search term and then scrolling over the candidates in Selectrum by pressing `<down>`, the scrolling gets slower and slower. I did some profiling and the main culprit is `orderless-default-pattern-compiler` which eats up 80% of the time.

**Comment by minad** [comment]
It seems before d1c0cbf everything was a nicely pure function which is now messed up with side effects. The Emacs design is just bad :(

**Comment by minad** [comment]
Okay, I can confirm that preview is the problem. When I disable preview in consult, the scrolling is faster and does not grind to a halt. But even when with disabled previews, d1c0cbf still leads to a noticeable slowdown in comparison to the before.

**Comment by minad** [comment]
I propose the following fix:

~~~ diff
diff --git a/orderless.el b/orderless.el
index b92e6dd..c004cce 100644
--- a/orderless.el
+++ b/orderless.el
@@ -444 +444,3 @@ compilers."
-         (unless (or (not minibuffer-completion-table)
+         (unless (or (not completion-category-overrides) ;; optimization!
+                     (not (minibufferp)) ;; check if we are in the minibuffer
+                     (not minibuffer-completion-table)
~~~

**Comment by minad** [comment]
After looking a bit closer at #31, I would also like to propose to revert d1c0cbf87ba7d927ec64c161ec3aac65b9643b61 and *not* implement #31. But I admit that it is a nice idea.

When I look at `completion-all-completions` and `completion--nth-completion` the complete metadata handling already happens there. It looks like you don't have access to the completion category in the completion style itself. This is by design. By accessing the `minibuffer-completion-table` from your pattern compiler you violate this design and the assumptions. For example by `consult--default-completion-filter` will not work, since it explicitly passes metadata, as is allowed by the `completion-all-completions` API.

**Comment by oantolin** [comment]
> When I look at `completion-all-completions` and `completion--nth-completion` the complete metadata handling already happens there. It looks like you don't have access to the completion category in the completion style itself. This is by design. By accessing the `minibuffer-completion-table` from your pattern compiler you violate this design and the assumptions. For example by `consult--default-completion-filter` will not work, since it explicitly passes metadata, as is allowed by the `completion-all-completions` API.

This is a convincing reason to revert and not implement the API @astoff suggested. I'll do that.

> Another idea is to support custom orderless completion styles with their custom associated orderless style dispatchers, e.g., 'my-orderless-style-for-consult-location with the associated custom dispatchers first-initialism, flex-if-twiddle, without-if-bang. Then the completion-category-overrides could just be used as it is supposed to be used by specifying the custom orderless completion style there, e.g., 'my-orderless-style-for-consult-location

This is a good idea.

**Comment by minad** [comment]
Thank you! I believe my counter-proposal is even better since it allows you to define multiple custom orderless styles with associated dispatchers such that you can switch between them at will. This will give us even more flexibility in the end I think, while being more robust at the same time. The only downside of the counter proposal is that it will probably require a bit more code and refactoring of the orderless API. I would probably also redefine the default `orderless` style in terms of the new mechanism.

Somehow like this?

~~~ elisp
(orderless-define-style 'orderless-default dispatchers...)
(orderless-define-style 'orderless-consult-location dispatchers...)

(orderless-set-dispatchers 'orderless-default dispatchers...)
~~~

Then you would have to add `orderless-default` to your `completion-styles`.

**Comment by minad** [comment]
I suggest we close this, reopen #31 and discuss alternatives ways to implement the feature in #31.
