### ISSUE TITLE
Remove orderless-transient-* variables

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#34]
These variables can be replaced by setting the "real" corresponding variables buffer-locally. This can be done in a `minibuffer-with-setup-hook`. Original comment in #31, https://github.com/oantolin/orderless/issues/31#issuecomment-763925202.

**Comment by oantolin** [comment]
I'll remove them gladly! I think when we added them @clemera and I just didn't think of the `setq-local` technique.

**Comment by minad** [comment]
Cool! I like when things get simpler :partying_face:

**Comment by oantolin** [comment]
> Cool! I like when things get simpler 🥳

Me too.
