### ISSUE TITLE
Better company configuration

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#35]
Using a unicode letter character.

~~~ elisp
         :map company-active-map
         ("," . (lambda () (interactive) (insert (propertize "ߊ" 'display " "))))
         ...
         (setq orderless-component-separator "[ ߊ]+")
~~~

Add this to the readme? This trick is by @clemera, see https://github.com/raxod502/selectrum/issues/419#issuecomment-771450196

**Comment by oantolin** [comment]
Oh, nice. I mention using & for Emacs Lisp, where it is allowed to be in identifiers, but this should work well in other languages too.

**Comment by oantolin** [comment]
Wait, I bet company only knocks you out of the pop up when you press space, so probably & works in any language.

At any rate the cool part of that trick is displaying the separator as a space.

**Comment by minad** [comment]
Yes, but you could actually want to complete &. Furthermore you may want to press a different key as separator.

**Comment by minad** [comment]
One should actually check if & works for every language than that would still be a reasonable choice I think. I assumed what you wrote in the README, that the character must be a valid identifier character. I assume letters always are, but maybe it is not the case for unicode characters. I still like the display as space and that the "separator behind the scene" is decoupled from the key I am pressing.

**Comment by minad** [comment]
Living happily on Corfu now :greece:
