### ISSUE TITLE
orderless renders counsel-rg ineffective

### ISSUE THREAD

**Issue by revrari** [oantolin/orderless#37]
If I add the following code to my `init.el` to activate `orderless` in Emacs, then `counsel-rg` no longer works in Emacs:
```
(require 'orderless)
(setq completion-styles '(orderless))
(setq ivy-re-builders-alist '((t . orderless-ivy-re-builder)))
```
Do you have any ideas how I might fix this problem?
Below is the code in my`init` file that pertains to `counsel-rg`:

```
(defvar my-rg-excludes '("~/personal" "~/computing" "~/deft" "~/emacs" "~/resources" "~/sermons")
  "List of directories to exclude from `counsel-rg' results.")

(define-advice counsel-rg
    (:around (fn &optional in dir opts &rest args) my-glob)
  "Exclude `my-rg-excludes' from `counsel-rg' results."
  (let ((dir (or dir default-directory)))
    (dolist (x my-rg-excludes)
      (let ((glob (and (file-in-directory-p x dir)
                       (file-relative-name (expand-file-name "**" x) dir))))
        (when glob (setq opts (concat "-g !" glob (and opts " ") opts))))))
  (apply fn in dir opts args))

 '(counsel-rg-base-command
   '("rg" "-M" "260" "--with-filename" "--no-heading" "--line-number" "--color" "never" "%s" "--no-hidden"))
```

**Comment by oantolin** [comment]
I don't have any experience with `counsel-rg`, but wouldn't be surprised if it is implemented by sending the query to ripgrep and not doing any filtering on the Emacs side. I think you should probably just disable orderless in the advice you put on `counsel-rg`

**Comment by oantolin** [comment]
If you want an alternative to `counsel-rg` that does work with orderless, I can recommend `consult-ripgrep` from [Consult](https://github.com/minad/consult). That command has a clever design: you type a query of the form `#args#filter`, `args` are passed to ripgrep, and the `filter` is used for Emacs's filtering. In particular if you use orderless, it will handle the `filter` part. I don't know if Consult's async command work with Ivy, though, maybe not yet.

**Comment by revrari** [comment]
Thank you for your recommendation, which I shall definitely test out. FYI I tinkered with things and setting the following variable has "apparently" fixed the problem. I will need to test it further. 
```
(setq ivy-preferred-re-builders
   '((ivy--regex-plus . "ivy")
     (ivy--regex-ignore-order . "order")
     (ivy--regex-fuzzy . "fuzzy")
     (orderless-ivy-re-builder . "orderless")))
```
Thanks for your wonderful package.

**Comment by minad** [comment]
Unfortunately consult async does not yet work with Ivy (See https://github.com/minad/consult/issues/212). I tried it once to add support but Ivy is complicated. Maybe I should ask for help on the Ivy issue tracker, but I believe that interest would be low, since you can always use Counsel with Ivy.

**Comment by revrari** [comment]
> I don't use ivy much these days and maybe don't remember exactly what `ivy-preferred-re-builders` is for. Does Ivy use whatever style is at the front of that list, and let you rotate the list with a key binding? So, with that configuration you are just using `ivy--regex-plus` until you rotate the list? If that is indeed how it works, you might want to put orderless at the front of the list and pick just one of the ivy styles for use with `counsel-rg`, and manually rotate whenever you run `counsel-rg`
> 
> But I think you can still use orderless everywhere except `counsel-rg` in an automatic fashion, instead of manually rotating `ivy-preferred-re-builders`. You can try instead of that configuration this other setting:
> 
> ```emacs-lisp
> (setq ivy-re-builders-alist '((counsel-rg . ivy--regex-plus) (t . orderless-ivy-re-builder)))
> ```

I have adopted your proposal.

**Comment by oantolin** [comment]
Use it for a while to see if it really works out for you. And if you find that to be an adequate workaround, we can close this issue.

**Comment by revrari** [comment]
Okay. Shall do. Thanks so much.
