### ISSUE TITLE
orderless-strict-leading-initialism highlighting with empty input

### ISSUE THREAD

**Issue by clemera** [oantolin/orderless#38]
When there is no input leading numbers get highlighted for some reason, to reproduce:

```elisp
(setq completion-styles '(orderless))
(setq orderless-matching-styles
      '(orderless-strict-leading-initialism))
(completing-read "Test: " '("1this" "2that" "nohighlight"))
```

**Comment by oantolin** [comment]
I'll look into it.

**Comment by oantolin** [comment]
It's not just numbers, any non-letters get highlighted. I thought that since they were matched in a non-capturing group, they wouldn't be highlighted, but apparently I don't know really know what orderless highlights. 😆

**Comment by oantolin** [comment]
Please test.

**Comment by clemera** [comment]
Can confirm its fixed, thanks!
