### ISSUE TITLE
keywords is not highlighted

### ISSUE THREAD

**Issue by jixiuf** [oantolin/orderless#4]

**Comment by oantolin** [comment]
True! I think I know how to do that, but it might be a little tricky.

**Comment by oantolin** [comment]
It wasn't tricky, I was just misunderstanding something. I believe ae36760 should fix this, please test.

**Comment by protesilaos** [comment]
Highlighting works, but it is giving false positives which either have to do with the font lock itself or the underlying completion.

I applied a green background to illustrate the issue.  You can see it is matching what I typed in, but it also highlights `e` in green background while suggesting it is matching `fo` in "fonts" (third line).  The latter retains the original completion styles, which may hint that something else is at play.

![Screenshot at 2020-04-14 20-14-25](https://user-images.githubusercontent.com/12828033/79254280-2be2e500-7e8d-11ea-80c1-54dd1a91c961.png)

**Comment by oantolin** [comment]
Oh. I'll look into it. Thanks!

**Comment by oantolin** [comment]
I was mutating the strings: they were keeping all the faces I ever added.

Since there is no convenient time to remove the faces, I decided instead to make a copy of the strings first (aad0aa8). This should take care of the ghostly remnants of previous propertizing. Please test.

**Comment by protesilaos** [comment]
It works!

**Comment by oantolin** [comment]
Is it OK to close this issue now?

**Comment by protesilaos** [comment]
I think yes, though @jixiuf may still wish to offer some more feedback.

**Comment by jixiuf** [comment]
It is Ok to close. Thanks.
