### ISSUE TITLE
Unused lexical variable warning

### ISSUE THREAD

**Issue by bdarcus** [oantolin/orderless#41]
Not sure if this is significant, but FYI doom issues the following warning:

```
In toplevel form:
autoloads.28.0.50.el:698:168: Warning: Unused lexical variable
    ‘orderless-match-faces’
```

**Comment by oantolin** [comment]
This sounds Doom specific to me:

1. The `orderless-autoloads.el` created by `package.el` does not contain any mention of `orderless-match-faces` at all.
2. In `orderless.el`, `orderless-match-faces` is not a lexical variable (it's defined with `defcustom` making it dynamically scoped) and it is not unused.

So I have no idea what the message is about.

**Comment by bdarcus** [comment]
OK!
