### ISSUE TITLE
Add literal to default matching styles?

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#42]
See https://github.com/raxod502/selectrum/issues/429#issuecomment-804768346 and discussion in https://github.com/raxod502/selectrum/issues/429. cc @clemera @jaor

**Comment by oantolin** [comment]
Sure, why not? The only thing that gives me pause is that you said elsewhere it didn't work for you. Let's figure out why not before doing anything.

**Comment by minad** [comment]
Yes, sure. I wonder why it didn't work like this. Otherwise I don't see big downsides of doing this. And one could use style dispatchers to mark certain parts of the input as explicitly literal/regexp. However style dispatchers will also introduce problems regarding to the matching of exact inputs.

**Comment by minad** [comment]
I set `(setq orderless-matching-styles '(orderless-regexp orderless-literal orderless-initialism))`.

If I invoke `consult-line` and enter `[0-9`, then it does not match anything. As soon as I close `[0-9]` it matches both `1329817321` and `[0-9]`. This is the bug.

**Comment by oantolin** [comment]
Mmh. Does changing the order of `orderless-regexp` and `orderless-literal` make any difference (it shouldn't, but if it does that might be a clue)?

**Comment by minad** [comment]
No difference.

**Comment by oantolin** [comment]
I'll look into it. I thought my tests covered this case...

**Comment by oantolin** [comment]
It happens because with those matching styles (with any list of matching styles that includes `orderless-regexp`), the incomplete `[0-9` gets compiled to a malformed regexp. Mmh.

**Comment by minad** [comment]
Hmm, I see. Is it hard to detect if a regexp is valid and only include it in that case?

**Comment by oantolin** [comment]
I'm looking into the best way to do it. Maybe there is something better, but matching against anything (an empty string, for example) should work: if it returns it's valid, if it errors it's not.

**Comment by oantolin** [comment]
It looks like `re-builder` uses that strategy, so I will too.

**Comment by minad** [comment]
I wonder why the current approach didn't lead to errors. Is this because the matching happens deep inside `all-completions` in the c code?

**Comment by oantolin** [comment]
Oh, no, I already have a `condition-case` to catch errors in matching and just report no matches.

**Comment by oantolin** [comment]
I think I'll have the `orderless-regexp` style match invalid regexps literally. This seems to be the least surprising behavior.

**Comment by oantolin** [comment]
OK, done. a609004d5fc3d2755545069187b6362e7a92d017

Now I'll add `orderless-literal` to the default matching styles.

**Comment by minad** [comment]
Great, thanks! Nice that we also uncovered a bug through this discussion. cc @jaor

**Comment by oantolin** [comment]
I thought the `(defalias 'orderless-regexp #'identity)` implementation was cute, I'm kind of sad to see it go. 😛

**Comment by minad** [comment]
You could introduce `(defalias 'orderless-regexp-I-know-what-I-am-doing #'identity)`.

**Comment by jaor** [comment]
On Tue, Mar 23 2021, Daniel Mendler wrote:

> Great, thanks! Nice that we also uncovered a bug through this
> discussion. cc @jaor

Yes, nice outcome. Thanks.

**Comment by jaor** [comment]
BTW, another place where this bit me is when running an embark action
that asks for confirmation, which inserts the candidate in the prompt.
For instance (without orderless-literal), if i consult-buffer, make a
buffer called `*<w3m>*<1>` current, embark-action and k to kill it, one
cannot then RET to kill it.

**Comment by oantolin** [comment]
This why I always bind `M-RET` to `exit-minibuffer`, I get sick of any completion UI telling what I can cannot submit as input. All of them do it in different circumstances, I think.
