### ISSUE TITLE
Can I match str1 OR str2 instead of str1 AND str2?

### ISSUE THREAD

**Issue by linwaytin** [oantolin/orderless#47]
Sometimes I would like to find out items with `str1` or `str2`, instead of `str1` AND `str2`.
Is there a way like `str1|str2` such that it can match both `foo-str1` and `foo-str2`?

**Comment by oantolin** [comment]
Basically you just need a backslash. If you use the regexp matching style (which is one of the defaults) you can use regexps, but they use Emacs regexp syntax, so `str1\|str2` would match `str1` or `str2`.

**Comment by minad** [comment]
@oantolin I also thought about this feature before. You may remember when we talked about the (useless) negation operator. But maybe it would be useful to support an OR operator? `str1 str2 str3 | str4 str5 str6`?

**Comment by oantolin** [comment]
I guess it could be added. Is it really useful? I've always felt the regexp level or, `\|`, was sufficient.

**Comment by minad** [comment]
It is probably sufficient as is. I don't know if I would use such an operator if it would exist. The bad thing is that "str1 str2 |" would show all candidates again as soon as you type the "|". It will be weird to use I guess.

**Comment by linwaytin** [comment]
Thank you!
