### ISSUE TITLE
Issue with `ledger-mode` and `completion-ignore-case`

### ISSUE THREAD

**Issue by plattfot** [oantolin/orderless#52]
It seems `orderless` does not respect `completion-ignore-case` when completing accounts in ledger.

# Repro:

## Using
`emacs-27.2`
`orderless` commit d97a91f
[ledger-mode](https://github.com/ledger/ledger-mode) commit [58a2bf57](https://github.com/ledger/ledger-mode/tree/58a2bf57af9289daeaac6892fa4008ea8255b205)

## Steps
Create these two files
`/tmp/init.el`
```elisp
(require 'ledger-mode)
(require 'orderless)
(add-to-list 'auto-mode-alist '("\\.dat\\'" . ledger-mode))
(setq tab-always-indent 'complete
      completion-ignore-case t
      ledger-complete-in-steps t
      completion-styles '(orderless))
```
`/tmp/ledger.dat`
```
2015/10/12 Exxon
    Expenses:Auto:Gas         $10.00
    Liabilities:MasterCard   $-10.00

2021/05/15 Exxon
    Expenses:au
```
Then run
```sh
emacs -Q -L /load/path/to/orderless -L /load/path/to/ledger-mode -l /tmp/init.el +6:16 /tmp/ledger.dat
```
and then run `M-x completion-at-point` which will give the error `No match`. If you change `au` to `Au` emacs will expand it to `Auto:` as expected.

If you instead use:
`/tmp/init.el`
```elisp
(require 'ledger-mode)
(require 'orderless)
(add-to-list 'auto-mode-alist '("\\.dat\\'" . ledger-mode))
(setq tab-always-indent 'complete
      completion-ignore-case t
      ledger-complete-in-steps t)
```
I.e. not setting `completion-styles` to `'(orderless)`,  emacs will expand `au` to `Auto:` as expected.

Not sure if this is an issue with `ledger-mode` or `orderless`, but given that this issue shows up when I use `orderless` I'll start here. And to clarify this only happens in `ledger-mode`, `orderless` will ignore the case when running `M-x` for example.

Thanks

**Comment by minad** [comment]
Adjust `orderless-smart-case`?

**Comment by oantolin** [comment]
Weird. I'll attempt to reproduce, but the fact that orderless does ignore case in other completions sounds like it's not a bug in orderless. I also don't think `orderless-smart-case` should be the culprit, because you tested with `au`, in lowercase.

**Comment by oantolin** [comment]
This will be difficult for me to reproduce: ledger-mode does not seem to want to complete at all here. Do I need the ledger executable for completion?

**Comment by plattfot** [comment]
> This will be difficult for me to reproduce: ledger-mode does not seem to want to complete at all here (this is _without_ loading orderless). Do I need the ledger executable for completion?

Yeah, sorry I think you need ledger installed for it to work. I'm using `ledger-3.2.1`

> Adjust `orderless-smart-case`?

Interestingly if I set `orderless-smart-case` to `nil` it seems to work. I.e like this
```
(require 'ledger-mode)
(require 'orderless)
(add-to-list 'auto-mode-alist '("\\.dat\\'" . ledger-mode))
(setq tab-always-indent 'complete
      completion-ignore-case t
      ledger-complete-in-steps t
      orderless-smart-case nil
      completion-styles '(orderless))
```
So it seems there might be something with `orderless-smart-case`, as it will not work if I use
```
(require 'ledger-mode)
(require 'orderless)
(add-to-list 'auto-mode-alist '("\\.dat\\'" . ledger-mode))
(setq tab-always-indent 'complete
      ;; completion-ignore-case t
      ledger-complete-in-steps t
      orderless-smart-case t
      completion-styles '(orderless))
```

**Comment by oantolin** [comment]
Now I'm very curious. Let's see if I have disk space to install ledger and it's rather large dependencies (Python 2.7! after all the effort I went through to get rid of it!).

**Comment by oantolin** [comment]
Yep. Can spare 40MB.

**Comment by oantolin** [comment]
I installed ledger and I now see what's going on! In your example you are completing the string `Expenses:au`, with a capital `E`. So with `orderless-smart-case` what happens is that since the string contains at least one capital letter, the completion is done case sensitively.

Sadly, this behavior seems correct. I bet it is surprising since you probably thought you were completing the string `au`, not `Expenses:au`! (I was certainly surprised by that.) If you try completing `expenses:au` it does work.

I'm not sure there is anything I can do about this on the Ordereless side.

**Comment by plattfot** [comment]
> I installed ledger and I now see what's going on! In your example you are completing the string `Expenses:au`, with a capital `E`. So with `orderless-smart-case` what happens is that since the string contains at least one capital letter, the completion is done case sensitively.
> 
> Sadly, this behavior seems correct. I bet it is surprising since you probably thought you were completing the string `au`, not `Expenses:au`! (I was certainly surprised by that.) If you try completing `expenses:au` it does work.

Oh, that makes total sense and really sneaky. Yeah, I was expecting it was just expanding `au`. 

> I'm not sure there is anything I can or should do about this on the Orderless side, but I am certainly open to suggestions!

In my opinion this is nothing `orderless` should handle, instead this seems more of an issue on `ledger-mode`'s side. For now I'll just turn off `orderless-smart-case` for ledger mode and open up an issue on their side and see what they say.

Thanks again for looking into this and say sorry to your 40MB that had to deal with python 2.7!

**Comment by plattfot** [comment]
And for other people that stumble across this issue, here is how I'm working around it.
```elisp
(add-hook 'ledger-mode-hook (lambda () (setq-local orderless-smart-case nil)))
```

**Comment by oantolin** [comment]
> Thanks again for looking into this and say sorry to your 40MB that had to deal with python 2.7!

No problem! I feel I should explain why I'm so constrained for space. The computer I use most often is an old Chromebook with an 8GB drive. I run Emacs in a Linux VM (Chrome OS comes with one! And it's really well integrated into the system). I don't think I can shrink the file the VM uses a hard drive (I knew it couldn't be done at some pint but haven't checked if updates have changed that) so I have to be careful not to have it grow too much or I have to nuke the VM and reinstall some things, which is doable but pretty annoying.

**Comment by plattfot** [comment]
Those are some tight constrains, I hope you didn't any take offense about what I said. If you did, I apologize.

And I can happily report that things have been working smoothly since I applied the workaround.

**Comment by oantolin** [comment]
> I hope you didn't any take offense about what I said

No offense taken at all!

I just wanted to explain why I was worried about disk space in 2021. I thought that without explaining it I would came across as a weirdo. 😛

**Comment by plattfot** [comment]
> No offense taken at all!

Cool!
 
> I just wanted to explain why I was worried about disk space in 2021. I thought that without explaining it I would came across as a weirdo.

Haha, no worries. I didn't find anything weird about it.
