### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by yoctocell** [oantolin/orderless#53]
There hasn’t been a new for release for about a year, there has also
been some changes to the core API, like renaming
‘orderless-default-pattern-compiler’ to ‘orderless-pattern-compiler’,
which has caused the vertico package to complain.  I think it might be
time to tag a new release :)

**Comment by oantolin** [comment]
Why would vertico complain about that?

But yes, a new release is a good idea. (I like Melpa so I forget the  erosion numbers are used for something...)

**Comment by yoctocell** [comment]
On Sun, May 16 2021, Omar Antolín Camarena wrote:

> Why would vertico complain about that?

I am using the latest release of orderless which has a function called
‘orderless-default-pattern-compiler’, but the latest release of vertico
calls ‘orderless-pattern-compiler’, which doesn’t exist.

  Error in post-command-hook (vertico--exhibit): (void-function orderless-pattern-compiler)

> But yes, a new release is a good idea. (I like Melpa so I forget the
> erosion numbers are used for something...)

I use Guix which usually only contains the latest release, I could
create an orderless package that uses the source from HEAD, but it would
be nicer to tag a release and update the upstream Guix package. :)

**Comment by oantolin** [comment]
Done.

**Comment by minad** [comment]
Vertico implements deferred highlighting for a few completion styles including orderless. This led to problems here.

**Comment by oantolin** [comment]
> Vertico implements deferred highlighting for a few completion styles including orderless. This led to problems here.

I had forgotten that, but looked it up in the Vertico source when @yoctocell mentioned it.
