### ISSUE TITLE
orderless+initialism doesn't work

### ISSUE THREAD

**Issue by iyefrat** [oantolin/orderless#54]
I tried to add the following recommended config from the README on a vanilla install of orderless:

```emacs-lisp
(orderless-define-completion-style orderless+initialism
  (orderless-matching-styles '(orderless-initialism
                               orderless-literal
                               orderless-regexp)))
(setq completion-category-overrides
      '((command (styles orderless+initialism))
        (symbol (styles orderless+initialism))))
```
but this doesn't seem to actually add initialism matching to e.g. `M-x` or `C-h f` (tested with `dk` for `describe-key`).

**Comment by oantolin** [comment]
I can't reproduce this problem, either with my own config or from `emacs -Q`. In my tests `dk` did match `describe-key`, as desired.

**Comment by oantolin** [comment]
The only thing I can think of is that maybe you are using a version of Emacs for which `M-x` does not report the `command` completion category. Try installing [Marginalia](https://github.com/minad/marginalia), activating `marginalia-mode`, and trying again.

**Comment by oantolin** [comment]
In fact, now that I think of it, while starting with some version (maybe 27.2?) Emacs does report the `command` completion category for `M-x`, I think it still doesn't report any category for `C-h f`, so you do need Marginalia anyway.

**Comment by iyefrat** [comment]
I am running this on emacs 27.2. When reproducing this on `emacs -Q`,  installing `marginalia` and activating `marginalia-mode` after the `orderless` setup does get it to work (however it doesn't work on `M-x` without `marginalia`).

 Thing is, I originally encountered this problem in the doom emacs selectrum module PR (hlissner/doom-emacs#4664), where orderless is eagerly loaded (with a `use-package` `:demand t`), and `marginalia-mode` is hooked to first input. So from what you're saying it should work there, but it doesn't.
 
  Any ideas? If not, feel free to close this issue as this problem is obviously out of scope.

**Comment by oantolin** [comment]
> I am running this on emacs 27.2. When reproducing this on `emacs -Q`, installing `marginalia` and activating `marginalia-mode` after the `orderless` setup does get it to work (however it doesn't work on `M-x` without `marginalia`).

I wasn't sure it the version where Emacs started reporting the `command` category for `M-x` was 27.2, your experiment indicates it must have started with Emacs 28, then.
 
> Thing is, I originally encountered this problem in the doom emacs selectrum module PR ([hlissner/doom-emacs#4664](https://github.com/hlissner/doom-emacs/pull/4664)), where orderless is eagerly loaded (with a `use-package` `:demand t`), and `marginalia-mode` is hooked to first input. So from what you're saying it should work there, but it doesn't.

> Any ideas? If not, feel free to close this issue as this problem is obviously out of scope.

That just sounds like Marginalia is loaded too late to help the first time. You probably see things work correctly the second time you try `M-x`, right? In my personal configuration I load Maginalia eagerly and I've never thought carefully about how much it could be delayed. Maybe you should just load it eagerly?

**Comment by oantolin** [comment]
At any rate, that example in the README should definitely mention you need Marginalia, I'll fix that.

**Comment by iyefrat** [comment]
> That just sounds like Marginalia is loaded too late to help the first time. You probably see things work correctly the second time you try M-x, right? 

Nope, the problem persists on multiple subsequent runs of `M-x`/`C-h f`.

> Maybe you should just load it eagerly?

This doesn't change anything either.

**Comment by oantolin** [comment]
> This doesn't change anything either.

But it did when you tested in `emacs -q`, right? You are activating `marginalia-mode` in addition to loading the marginalia package, right?

I could take a look at how you are loading Marginalia, but not being familiar with Doom, I am unlikely to understand.

**Comment by oantolin** [comment]
I took a look at the code you are using to activate marginalia-mode in the Doom module. As predicted I have no idea what's wrong, it seems very sensible. Sorry.

**Comment by iyefrat** [comment]
I've managed to narrow it down to something in the `selectrum` configuration, as when I comment out the following it works in doom:

```emacs-lisp
(use-package! selectrum
  :hook (doom-first-input . selectrum-mode)
  :init
  (setq selectrum-display-action nil
        selectrum-num-candidates-displayed 15
        selectrum-extend-current-candidate-highlight t)
  (when (featurep! +prescient)
    (setq completion-styles '(substring partial-completion)))
  :config
  (setq selectrum-fix-vertical-window-height 17
        selectrum-max-window-height 17
        projectile-completion-system 'default)
  (defadvice! +selectrum-refresh-on-cycle (&rest _)
    :after 'marginalia-cycle
    (when (bound-and-true-p selectrum-mode) (selectrum-exhibit)))

  (defun +selectrum/backward-updir ()
    "Delete char before or go up directory for file cagetory selectrum buffers."
    (interactive)
    (if (and (eq (char-before) ?/)
             (eq (selectrum--get-meta 'category) 'file))
        (let ((new-path (minibuffer-contents)))
          (delete-region (minibuffer-prompt-end) (point-max))
          (insert (abbreviate-file-name
                   (file-name-directory
                    (directory-file-name
                     (expand-file-name new-path))))))
      (call-interactively 'backward-delete-char)))

  (map! :map selectrum-minibuffer-map
        "C-o"       #'embark-act
        "C-c C-o"   #'embark-export
        "C-c C-e"   #'+selectrum/embark-wgrep
        [backspace] #'+selectrum/backward-updir))
```

**Comment by iyefrat** [comment]
wait scratch that, just turning on `selectrum-mode` stops it from working regardless of that configuraiton.

**Comment by iyefrat** [comment]
I think the fact that the `file` override working might have been a red herring, I recall @minad telling me once that selectrum comes with it's own partial completion thing, separate from that.

**Comment by iyefrat** [comment]
Okay this is definitely some sort of nontrivial doom thing, as running `emacs -Q` and evaling the following gets the initialisms to work with selectrum:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'orderless)
(require 'orderless)
(setq completion-styles '(orderless))
(orderless-define-completion-style orderless+initialism
  (orderless-matching-styles '(orderless-initialism
                               orderless-literal
                               orderless-regexp)))
(setq completion-category-overrides
      '((command (styles orderless+initialism))
        (symbol (styles orderless+initialism))))
(package-install 'marginalia)
(marginalia-mode)
(package-install 'selectrum)
(selectrum-mode +1)
```

given that, I'll close the issue. Thank you for your time!

**Comment by oantolin** [comment]
Sorry, I couldn't be of more help. Good luck figuring this out.

**Comment by minad** [comment]
**Copying the comment I made in https://github.com/hlissner/doom-emacs/pull/4664:**

The problem is that you overwrite the Selectrum filter and highlighting function with the orderless filter/highlighting function. This bypasses the completion styles logic. If you remove these function overrides you should be good. Unfortunately the highlighting won't be optimized then until raxod502/selectrum#539 is implemented.
