### ISSUE TITLE
Adding Orderless to GNU ELPA

### ISSUE THREAD

**Issue by oantolin** [oantolin/orderless#57]
I'm hoping to add Orderless to GNU ELPA at some point and to this end I just signed the FSF copyright assignment papers. I believe all contributors whose lines added and deleted sum to more than 8 have also signed the papers except perhaps for @noctuid. So, @noctuid, have you already done the FSF copyright assignment? And if not, would you be willing to do so?

**Comment by oantolin** [comment]
Just a friendly reminder, @noctuid, have you signed the FSF copyright assignment papers?

**Comment by noctuid** [comment]
Sorry for the late response. I previously looked into getting the paper work signed and didn't get anywhere because my manager had just quit and I didn't clearly have a manager for a long time. I will ask my manager to sign the disclaimer next week.

**Comment by astoff** [comment]
Hi @noctuid, is there any progress on this matter?

**Comment by noctuid** [comment]
Some back and forth with legal. I'm waiting for a response from them. My manager said it will probably take a long time to get the disclaimer signed.

**Comment by minad** [comment]
Okay, let's ping Stefan @monnier about Orderless on GNU ELPA. The package has been prepared for inclusion there!

**Comment by minad** [comment]
I forgot, the package header still requires adjustment in order to complete the preparations.

**Comment by oantolin** [comment]
Done. 7385bcf3c1201cb2d2e4ae8c260deded3fa388df

**Comment by monnier** [comment]
Oh, this is great!
I just pushed it to `elpa.git`.  It should appear shortly on a GNU ELPA near you.  Thanks!

**Comment by oantolin** [comment]
Wow, that was fast. thanks @monnier!

**Comment by minad** [comment]
@oantolin The package did not yet appear on ELPA since you have to tag a new release 0.7 first.

**Comment by oantolin** [comment]
Thanks for letting me know, @minad. I bumped the version number an tagged a release.

**Comment by minad** [comment]
This can be closed?

**Comment by oantolin** [comment]
Right!
