### ISSUE TITLE
question: how to use orderless-strict-*-initialism when the definition of word has changed `modify-syntax-entry`

### ISSUE THREAD

**Issue by d1egoaz** [oantolin/orderless#60]
Hello

I've modified the definition of words to include `-` and `_`, it looks like this change affects how orderless work with `orderless-strict-*-initialism`

```lisp
(defun diego--treat-chars-as-word-char ()
  (modify-syntax-entry ?_ "w")
  (modify-syntax-entry ?- "w"))
(add-hook 'after-change-major-mode-hook #'diego--treat-chars-as-word-char)
```
When I disabled above code, `orderless-strict-*-initialism` works as expected. 

I've tried setting

```lisp
  (setq completion-pcm-word-delimiters "-_./:| ")
```
but it doesn't have any effect on orderless.

thanks!

**Comment by d1egoaz** [comment]
a workaround that worked for me, is to modify the syntax table for specific modes

```lisp
  (modify-syntax-entry ?_ "w" emacs-lisp-mode-syntax-table)
  (modify-syntax-entry ?- "w" emacs-lisp-mode-syntax-table)

  (modify-syntax-entry ?_ "w" org-mode-syntax-table)
  (modify-syntax-entry ?- "w" org-mode-syntax-table)
```

**Comment by oantolin** [comment]
The current definition of `orderless--strict-*-initialism` uses the `[:word:]` class that depends on syntax tables, I'll change it to `[:alpha:]` (which doesn't), since I think that behavior is less surprising. (But I have to say I am also a little surprised someone would want to treat `-` and `_` are word constituents!)

**Comment by d1egoaz** [comment]
> (But I have to say I am also a little surprised someone would want to treat - and _ are word constituents!)

I'm used to threat variables as a whole words, maybe because development background 🤷 , most of the time I'm interested in the whole variable name and not just part of it, I also use evil and move using b,e, w to move between variables/words.


I tested the latest master and it didn't work for me

with:
```
(modify-syntax-entry ?_ "w")
(modify-syntax-entry ?- "w")
```

<img width="487" alt="image" src="https://user-images.githubusercontent.com/950087/121736996-242cc980-caad-11eb-92b2-8ca33f469b9f.png">

and then use `db,` to kick in `orderless-strict-initialism`
<img width="817" alt="image" src="https://user-images.githubusercontent.com/950087/121736977-1d05bb80-caad-11eb-87cc-930423bed00e.png">


without `modify-syntax-entry` :
<img width="746" alt="image" src="https://user-images.githubusercontent.com/950087/121737378-9f8e7b00-caad-11eb-889d-f6a387b03810.png">


This is my config:
```
  ;; adapted from https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer
  ;; Recognizes the following patterns:
  ;; * ~flex flex~
  ;; * =literal literal=
  ;; * ,initialism initialism,
  ;; * !without-literal without-literal!
  ;; * .ext (file extension)
  ;; * regexp$ (regexp matching at end)
  (defun diego/orderless-dispatch (pattern _index _total)
    (cond
     ;; Ensure that $ works with Consult commands, which add disambiguation suffixes
     ((string-suffix-p "$" pattern) `(orderless-regexp . ,(concat (substring pattern 0 -1) "[\x100000-\x10FFFD]*$")))
     ;; File extensions
     ((string-match-p "\\`\\.." pattern) `(orderless-regexp . ,(concat "\\." (substring pattern 1) "[\x100000-\x10FFFD]*$")))
     ;; Ignore single !
     ((string= "!" pattern) `(orderless-literal . ""))
     ;; Without literal
     ((string-prefix-p "!" pattern) `(orderless-without-literal . ,(substring pattern 1)))
     ((string-suffix-p "!" pattern) `(orderless-without-literal . ,(substring pattern 0 -1)))
     ;; Initialism strict matching
     ((string-prefix-p "," pattern) `(orderless-strict-initialism . ,(substring pattern 1)))
     ((string-suffix-p "," pattern) `(orderless-strict-initialism . ,(substring pattern 0 -1)))
     ;; Literal matching
     ((string-prefix-p "=" pattern) `(orderless-literal . ,(substring pattern 1)))
     ((string-suffix-p "=" pattern) `(orderless-literal . ,(substring pattern 0 -1)))
     ;; Flex matching
     ((string-prefix-p "~" pattern) `(orderless-flex . ,(substring pattern 1)))
     ((string-suffix-p "~" pattern) `(orderless-flex . ,(substring pattern 0 -1)))))

  (setq orderless-matching-styles '(orderless-regexp orderless-strict-initialism))
  (setq orderless-style-dispatchers '(diego/orderless-dispatch))

```

**Comment by d1egoaz** [comment]
@oantolin feel free to revert to the original behaviour.

[This](https://github.com/oantolin/orderless/issues/60#issuecomment-858152983) works perfectly fine for me, these are the only modes where I need to change the word definition.


And thanks again for such an amazing package.
