### ISSUE TITLE
Is there a way to get flex orderless completions?

### ISSUE THREAD

**Issue by pushqrdx** [oantolin/orderless#62]
I wonder if it's possible to set orderless to match `package-delete` by typing either `padelete` and/or `delepack` 
setting completion style to orderless-flex only achieves the former

**Comment by oantolin** [comment]
Well, if you are willing to add spaces, `pa delete` and `dele pack` both match `package-delete` even with just the literal matching style. I think this is what I recommend: turn off flex, and just add spaces to your input. You can do it liberally, for example, I never remember if the command is `package-auto-remove` or `package-autoremove` so I conservatively type `au re pa` and it would match either way.

But if you really want `adeeeplt` to match `package-delete`, you can replace the `orderless-pattern-compiler`:

```elisp

(defun orderless-ultraflex (pattern &optional _styles _dispatchers)
  (mapcar #'string pattern))

(advice-add 'orderless-pattern-compiler :override #'orderless-ultraflex)
```

I suspect you won't _really_ like the letter matching in absolutely any order.

**Comment by pushqrdx** [comment]
@oantolin yeah i knew about adding spaces i just thought that just like i can type `padelete` to get `package-delete there might be a way to also type `deletepa` to get the same result

**Comment by oantolin** [comment]
> there might be a way to also type `deletepa` to get the same result

You can try the advice in my previous comment, I'd say that is a way to get the same result.

**Comment by pushqrdx** [comment]
@oantolin for me it just started matching everything, in kinda random way

**Comment by oantolin** [comment]
Well, not everything, just things with those letters in any order, which is what I thought you wanted.

But yes, that does typically lead to way too many matches, which is why I predicted you wouldn't like it. For my taste even flex matching produces too many matches.
