### ISSUE TITLE
Possible to match with buffers whose name starts with a space?

### ISSUE THREAD

**Issue by iquiw** [oantolin/orderless#68]
With default `completion-styles`,

1. Start emacs
   ```console
   $  emacs -Q -l vertico/vertico.el -l orderless/orderless.el --eval '(vertico-mode)'
   ```
2. Type <kbd>C-x b</kbd>.
3. Type <kbd>SPC</kbd>.

Then the following buffers are displayed.
![image](https://user-images.githubusercontent.com/238681/125368553-65b6da00-e3b5-11eb-92c4-641ccfdaa26e.png)

After setting the following configuration,
```emacs-lisp
(setq completion-styles '(orderless))
(setq completion-category-defaults nil)
(setq orderless-component-separator 'orderless-escapable-split-on-space)
```

Typing <kbd>\SPC</kbd> shows no buffer.
![image](https://user-images.githubusercontent.com/238681/125368688-cb0acb00-e3b5-11eb-8fe2-ba9bf88930bc.png)

Is it possible to display these buffers with `orderless` completion style only?

**Comment by oantolin** [comment]
By default orderless splits on spaces before doing anything else. You can configure orderless to let you escape spaces by setting `orderless-component-separator` to `orderless-escapable-split-on-space`. Alternatively you can keep the default splitting on spaces and use the regexp `\s-` to match a space.

**Comment by iquiw** [comment]
As written in the first comment, I already set `orderless-component-separator` to `orderless-escapable-split-on-space`.

**Comment by oantolin** [comment]
Oh, sorry, I missed that. This seems very odd then. I'll look into it.

**Comment by oantolin** [comment]
Oh, I think those hidden buffers (that's what buffers that start with space are called) are handled specially. I tried the experiment you suggested but not only with `orderless`, I also tried `substring`, `basic` and `partial-completion`, and the hidden buffers only match with `basic` not with `substring` or with `partial-completion`. So `basic` does something special here.

**Comment by oantolin** [comment]
I am curious to find out exactly what's going on, but for now, I suggest adding `basic` to the completion overrides for category `buffer` if you need this functionality.

**Comment by minad** [comment]
This sounds like the usual problem with dynamic completion tables which only work with `basic`.

**Comment by iquiw** [comment]
Thanks for the comments.

Since I don't much like `(basic orderless)` styles, I use the following code to display hidden buffers.
```emacs-lisp
(switch-to-buffer
 (consult--read (internal-complete-buffer " " nil t)
                :prompt "Switch to buffer: "
                :require-match t
                :category 'buffer))
```
