### ISSUE TITLE
SPC before existing group takes point to end of input

### ISSUE THREAD

**Issue by protesilaos** [oantolin/orderless#7]
For this description, consider `_` to mean the point.

I type `i plet_`.  Then `M-b` to `i _plet`. Here an `SPC` takes me to `i  plet_` (double space in between).

![Screenshot at 2020-04-17 06-40-41](https://user-images.githubusercontent.com/12828033/79529888-6b205a00-8076-11ea-9b7e-72972244c66f.png)

![Screenshot at 2020-04-17 06-40-55](https://user-images.githubusercontent.com/12828033/79529896-71aed180-8076-11ea-9cf9-8b0e5d04d3e2.png)

Not sure this is a bug given the whole point of orderless. Just noting the behaviour.

**Comment by oantolin** [comment]
It is a bug in the sense I didn't intend it to do that. :)

Thanks for reporting it. I've fixed it so that the point doesn't move (7f79dc2). And I also made an unrelated optimization (2813ffb), one that's really noticeable in describe-variable, for example.

**Comment by protesilaos** [comment]
Very well!
