### ISSUE TITLE
Better file completion: Remote file support, wildcards

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#72]
See https://github.com/minad/vertico#tramp-hostname-completion-and-wildcard-completion.

Any good idea where to keep this functionality? I assume we don't want to package it up as part of Orderless, since it is not really related.

**Comment by oantolin** [comment]
Well, Emacs _does_ put this functionality into completion-styles. Personally I think that's a bit of abuse, it's not really a completion-style thing. Maybe it should be handled in the file completion table? That's where environment variable interpolation is handled, right? But probably that's not very practical to change.

As you surmised I'm not too keen on having this in Orderless (but I'm willing to discuss it more). Also, isn't recommending the following simple and good enough?

```elisp
(setq completion-styles '(orderless)
      completion-category-overrides '((file (styles basic partial-completion))))
```

**Comment by minad** [comment]
No, wildcards don't work with basic. They are simply not supported and you won't see any completions when entering them. They work by postprocessing the result string after completion (works only with no require match of course).

**Comment by oantolin** [comment]
I though partial-completion supported wildcards.

**Comment by minad** [comment]
Let me check. I am glad I pinged you with this.

**Comment by minad** [comment]
One may still use a basic-remote completion style as given in https://github.com/minad/vertico#tramp-hostname-completion, which ensures that basic completion only sets in for remote paths. But using basic only is of course also sufficient, if one doesn't mind it kicking in more often.

~~~
(setq completion-styles '(orderless)
      completion-category-overrides '((file (styles basic-remote partial-completion))))
~~~
