### ISSUE TITLE
Avoid duplication in generated regular expressions

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#73]
It would be good to avoid literal duplicates if literal and regexp matching styles are used. This is probably not performance critical but it still feels like we could do a little bit better.

~~~ elisp
(orderless-pattern-compiler "literal") ;; ("\\(?:literal\\|literal\\)")
~~~

**Comment by oantolin** [comment]
Is just changing

```elisp
(rx-to-string `(or ,@regexps))
```

**Comment by minad** [comment]
Yes, only removing the duplicates, such that the common case of a literal search with literal+regexp styles gives a simpler regular expression:

~~~ elisp
(orderless-pattern-compiler "literal") ;; desired result: ("\\(?:literal\\)"), current result: ("\\(?:literal\\|literal\\)")
~~~

**Comment by oantolin** [comment]
OK, will do when I'm back at the computer.
