### ISSUE TITLE
Replace `orderless--highlight` with a more flexible and optimized function

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#74]
Like this function but written as a `cl-loop` and with additional support for multiple faces ;)

~~~ elisp
(defun consult--highlight-regexps (regexps str &optional beg end)
  "Highlight REGEXPS in STR from BEG to END.
If a regular expression contains capturing groups, only these are highlighted.
If no capturing groups are used highlight the whole match."
  (setq end (or end most-positive-fixnum))
  (dolist (re regexps)
    (when (string-match re str beg)
      (let ((i (if (match-beginning 1) 1 0)) m n)
        (while (setq m (match-beginning i))
          (when (< m end)
            (setq n (match-end i))
            (add-face-text-property
             m (if (> n end) end n)
             'consult-preview-match nil str))
          (setq i (1+ i)))))))
~~~

Call it `orderless-highlight-matches-single` and make it public? It is the lower level variant of `orderless-highlight-matches`and should not perform the compilation. Ideally `match-data` should be avoided since this leads to allocations and the function is potentially called many times by `consult--grep-format`. I would like to avoid every unnecessary allocation there. The optional beg and end arguments are needed to restrict the range. Then we can use this function in an orderless-specific replacement of `consult--command-highlight`. See https://github.com/minad/consult/issues/381#issuecomment-894275123.

**Comment by oantolin** [comment]
>  It is the lower level variant of `orderless-highlight-matches` and should not perform the compilation.

It seems closer to the current `orderless--highlight`, with two changes: accept an optional range, and use `match-beginning` and `match-end` instead of `match-data`.

**Comment by minad** [comment]
Yes, it is. It should replace orderless--highlight. My proposal is that orderless offers two functions as part of it's public API. orderless-highlight-matches and orderless-highlight-matches-single.

**Comment by oantolin** [comment]
I remember know why I used `match-data`: it's the only way I could figure out what all the groups were. Your function gives up at the first nil group even if there are later groups that did match.

```elisp
(progn
  (string-match "a\\(b\\)\\(c\\)\\|a\\(d\\)" "ade")
  (match-data))
;; Result: (0 2 nil nil nil nil 1 2)
```

In that example groups 1 and 2 are nil, but group 3 did match.

**Comment by minad** [comment]
Oh I missed this. You are right. There is one more issue. If you use these substring ranges, string-match does not work with ^. It seems that it is not possible to improve on your design. It is quite inefficient, on order to highlight one has to allocate the substring and the match-data must also be allocated. 

I close this for now. I have to rethink a few things.
