### ISSUE TITLE
Incompatible with the Python shell

### ISSUE THREAD

**Issue by astoff** [oantolin/orderless#79]
Orderless (but also the `flex` and `substring` styles) doesn't work with the Python shell completion. It's probably an issue there, but I wanted to ask if there is anything obviously wrong with this pattern:

```elisp
(defun python-shell-completion-at-point (&optional process)
  "Function for `completion-at-point-functions' in `inferior-python-mode'.
Optional argument PROCESS forces completions to be retrieved
using that one instead of current buffer's process."
  (setq process (or process (get-buffer-process (current-buffer))))
  (let* ((start {some computation that seems correct})
         (end (point))
         (completion-fn {a function which, when called with
                           (buffer-substring start end) as argument,
                           returns a list of possible completions
                           starting at start}))
    (list start end (completion-table-dynamic completion-fn))))
```

**Comment by minad** [comment]
Does it work with basic? It seems the dynamic completion table is fundamentally incompatible with style like orderless, partial-completion, initials, substring and flex since these styles pass the empty string as prefix argument to the completion table. If the dynamic python completion function relies on this prefix string to compute the completions it cannot work. `completion-table-dynamic` is an ill defined API and should not be used.

**Comment by minad** [comment]
If `completion-table-dynamic` would be avoided by the python shell completion function or if it would not rely on the given input string and accept the empty input string, the computation of the possible completion candidates would be far less efficient since all possible strings would have to be generated which are then post-filtered using the regexps generated by orderless. By using the prefix input string, the python shell can cull the set of possible completion candidates. So there is no good general solution for this problem - either generate all candidates (inefficiently) and work with `orderless` or only work with `basic`.

**Comment by astoff** [comment]
It works with basic.  And the Python shell already gets (or at least
could in principle get) a filtered list from the inferior process.

Assuming this is the case, what would be the canonical approach here?
Change `completion-fn` to ignore its string argument, or replace
`completion-table-dynamic` by something else?  (I am not into the ins
and outs of completion.)

**Comment by minad** [comment]
> Assuming this is the case, what would be the canonical approach here?
Change `completion-fn` to ignore its string argument, or replace
`completion-table-dynamic` by something else?  (I am not into the ins
and outs of completion.)

There is no good canonical solution as I mentioned before. The function should not ignore the string argument. It should return all possible completion strings if the string argument is empty, which is not efficient. If the string is non-empty, all possible completions with this prefix should be returned, such that the completion result is compatible with the `basic` completion style. I assume in the case of an empty string, the function returns no candidates, which leads to problems here.

I am afraid, the canonical solution is to not use `orderless`, but use `basic` :shrug:

**Comment by astoff** [comment]
> If completion-table-dynamic would be avoided by the python shell completion function or if it would not rely on the given input string and accept the empty input string, the computation of the possible completion candidates would be far less efficient 

I don't follow your reasoning. The way completion in the REPL works is, the REPL sends the contents of the current line to the Python inferior and receives a pre-filtered list of completions. This might or might not be efficient, but it's inescapable.

So I already have the precomputed candidates. I just need to pass it along in a way that pleases Emacs's completion system.

**Comment by minad** [comment]
I don't know how the Python package works internally. All I am saying is that the `orderless` completion style always passes the empty string as input to the dynamic completion function. This is not compatible with a completion function which relies on this input string to compute the candidates. In contrast, the `basic` completion style passes the input string directly to the completion function.

Try this:

~~~ elisp
(defun test-dynamic-table ()
  (completing-read "> "
                   (completion-table-dynamic
                    (lambda (arg)
                      (message "Input: %S" arg)
                      '("first" "second" "third")))))

(let ((completion-styles '(basic)))
  (test-dynamic-table))
(let ((completion-styles '(substring)))
  (test-dynamic-table))
(let ((completion-styles '(orderless)))
  (test-dynamic-table))
~~~

**Comment by oantolin** [comment]
I agree with everything @minad said, but want to add that while I don't really like the idea of treating the first component differently I'm starting to think it might be worth doing. I'd do something like: if the first component happens to compile to a regexp `r` that satisfies `(equal r (regexp-quote r))`, then call the completion table with it (and filter using the rest of the regexps obtained from the user input). I'd have to rename the package to `mostly-orderless`, though. 😛

**Comment by minad** [comment]
Why not add a configuration variable `orderless-use-prefix`? Then the user can define a `mostly-orderless` completion style with `orderless-define-completion-style`. :smile:

**Comment by minad** [comment]
Instead of relying on the criterion `(equal r (regexp-quote r))` you could always treat the first token as literal if `orderless-use-prefix` is true. That would be simpler and more predictable.

**Comment by oantolin** [comment]
I guess. How about this idea: if any of the components compiles to an anchored regexp of the form `^r` with `(equal r (regexp-quote r))`, then take the first such component and pass it to the completion table? No configuration options.

**Comment by oantolin** [comment]
You'd need an explicit `^` to request the behavior, but at least it makes sense.

**Comment by oantolin** [comment]
Ah, but that probably wouldn't work for completion-at-point, would it? People don't want to type the `^` and even if they did, in their buffer, for most syntax tables it wouldn't be part of the symbol being completed.

**Comment by minad** [comment]
> I guess. How about this idea: if any of the components compiles to an anchored regexp of the form ^r with (equal r (regexp-quote r)), then take the first such component and pass it to the completion table? No configuration options.

I think this is not such a good idea, or at least it is an orthogonal idea. It would work as an additional optimization (if you check for ^ and check that the rest of the string is a literal), but it would not resolve the scenario we are talking about here. 

The issue here relies on the prefix of the input to be used as input to the completion table, since you trigger completion at point with TAB after having entered a certain prefix.

**Comment by minad** [comment]
> Ah, but that probably wouldn't work for completion-at-point, would it? People don't want to type the ^ and even if they did, in their buffer, for most syntax tables it wouldn't be part of the symbol being completed.

Yes, we wrote at the same time. It is still a good idea as optimization. However having such `^regexps` is a rare case so it is probably not be worth the complication.

**Comment by oantolin** [comment]
The configuration variable is viable, I'm just trying to explore other options a bit to see if we can't come up with something even better. How about doing the `^` optimization and then people who want to treat the first component specially just use a style dispatcher that adds a `^` to the first component?

**Comment by oantolin** [comment]
I could even add such a style dispatcher to orderless so people don't have to write the 2 line function.

**Comment by minad** [comment]
I always forget how powerful the style dispatchers are. They can also dispatch by index, right? Then this is clearly the better solution. I don't feel strongly about to the optimization - I think there is no need to add this.

**Comment by astoff** [comment]
@minad I think you are overestimating my understanding of the completion system :-)

If you look at my (pseudo)code at the top of this issue, isn't it true that `completion-fn` will only ever be called with `(buffer-substring start end)` as argument? So I could as well replace `completion-fn` by `(let ((s (buffer-substring start end))) (lambda (_ignored) (funcall completion-fn s)`, and this is perfectly compatible with every completion style. _Oder?_

**Comment by astoff** [comment]
Okay, I think I get it now. Then I'm unsure whether or not to submit a patch to Emacs.

> Try this with Vertico:

Out of curiosity, why the completion table called with a full candidate sometimes when I turn Vertico off? Just typing `"f<tab>"` gives
```
Input: ""
Input: "first"
Input: ""
Input: "first" [2 times]
```

**Comment by minad** [comment]
> Then I'm unsure whether or not to submit a patch to Emacs.

There is nothing wrong here.

> Out of curiosity, why is the completion table called with a full candidate sometimes when I turn Vertico off?

For some of the actions of the programmable completion function (see the documentation of programmable completion or completing-read), the completion style is bypassed and the actual input string is passed to the completion function. This happens for example for the `metadata` or `boundaries` action. The completing read API is pretty incoherent :shrug:

**Comment by astoff** [comment]
> The completing read API is pretty incoherent

Sorry for the incoherent questions!

**Comment by oantolin** [comment]
> I always forget how powerful the style dispatchers are. They can also dispatch by index, right? Then this is clearly the better solution. I don't feel strongly about to the optimization - I think there is no need to add this.

Without the optimization having a style dispatcher prepend a `^` to the first component wouldn't actually fix the problem we're discussing.

**Comment by oantolin** [comment]
The optimization could also be simplified by only checking the first component for a `^`.

**Comment by oantolin** [comment]
> > The completing read API is pretty incoherent
 
> Sorry for the incoherent questions!

It's not your fault at all, the API is pretty hard to understand. To write orderless I actually had to read a good chunk of minibuffer.el, docs weren't enough for me.

**Comment by astoff** [comment]
> If completion-table-dynamic would be avoided by the python shell completion function

Actually, `completion-table-dynamic` could easily be avoided in the Python shell situation, by eagerly calling the `completion-fn`. Doing so would violate the following recommendation in the docstring of `completion-at-point-functions`:

```
NOTE: These functions should be cheap to run since they’re sometimes
run from ‘post-command-hook’; and they should ideally only choose
which kind of completion table to use, and not pre-filter it based
on the current text between START and END (e.g., they should not
obey ‘completion-styles’).
```

But in this case there seems to be no point in returning a dynamic completion table (which is fast to create) when querying it is potentially slow — or am I missing something? (The eager thing would have the same mild drawbacks of ignoring the string argument to the completion table, but nevermind.)

**Comment by minad** [comment]
It is not a good idea - as described in the documentation. Thr returned completion table would not work for `foo TAB DEL`, since then the returned completions would all start with `foo` instead of `fo`. Furthermore the eager completion would not be cheap. But these downsides are not that severe. With Company it even works in all scenarios, since Company reruns the Capf on every keypress. Corfu in contrast would be affected by this, since Corfu relies on capfs to respect the NOTE of the documentation.

**Comment by minad** [comment]
I had a longer discussion about this with the company maintainer @dgutov. Dmitry argues that recalling the capf every time is the safer and more robust approach in order to also support completion tables which do not respect the NOTE. He is right about this. However there are other technical reasons why Corfu is not recalling the capf every time (Corfu relies on the completion-in-region infrastructure), so Corfu only fully supports tables which respect the NOTE.

**Comment by astoff** [comment]
Now I realize that if you supply python.el's dynamic completion table to Vertico or Corfu, you could be doing a network transaction on every key press (I'm running the Python interpreter over Tramp a lot lately). Even without an SSH connection in between, each keypress would trigger some rather flimsy comint communication.

In fact, I've occasionaly seen some garbage dumped in the shell buffer while Corfuing. Clearly it was caused by the comint process hooks getting out of sync with the inferior process.

Now, if I patched python.el to compute the completions eagerly, you would have to contact the inferior process only once per completion-in-region session. You might freeze for a little bit after pressing TAB for the first time, but after that it would be fast to do further filtering. And one could use  flex or orderless, at the expense of `foo TAB DEL`.

So, in fact, following the NOTE seems pretty detrimental to Corfu and Vertico, at least in this rather particular case of comint-based completion.

**Comment by jdtsmith** [comment]
> Coincidentally, I had a longer discussion about this with the company maintainer @dgutov. Dmitry argues that recalling the capf every time is the safer and more robust approach in order to also support completion tables which do not respect the NOTE. 

This problem is deeply related to the discussion of LSP completion over [here](https://github.com/joaotavora/eglot/pull/737) and [here](https://github.com/minad/corfu/issues/59), where the "frequent CAPF table dumping" behavior of company was a topic.   A final takeaway for me was _Whose job is it ensure completions are fresh and reflect the buffer's content? The backend, or the UI?_.  

In the category of "reading meaning into the overly-vague docs" @joaotavora counters with the doctoring of `completion-at-point-functions` (see [this comment](https://github.com/joaotavora/eglot/discussions/726#discussioncomment-1291542)):

```
....
or a list of the form (START END COLLECTION . PROPS), where:
 START and END delimit the entity to complete and should include point,
 COLLECTION is the completion table to use to complete the entity, and
 PROPS is a property list for additional information.
....
```

with a strong focus on the singular word `entity`.   I.e. the `NOTE` and the `DOC` may stand in disagreement with each other.

**Comment by jdtsmith** [comment]
> Even without an SSH connection in between, each keypress would trigger some rather flimsy comint communication.

Yes.  And in addition to these overheads, you basically have to cache completion results for styles like orderless to have any value in these situations.  I have an (as yet unpublished) emacs package called `ipython-better` which hooks into iPython's completion sub-system within the shell (effectively replacing python.el's older shell callback).  I've run into basically the same issue.

Like LSP servers, such shell-driven backends do not (and cannot!) care one whit about Emacs' idea of the "input string".  They operate on the principle of "give me the buffer or entire line of input, as well as your place within it, and I will provide the relevant completions".  For instance, in `ipython-better`, my completion table _entirely ignores_ the string passed in, and hands the entire line of input off to iPython's completion system, caching the results.  iPython's completion system then tells _me_ what part of the text it is completing.  So the CAPF concept of "give me all possible completions for this input over this range, and I'll sort through them myself" is clearly deeply incompatible with these type of remote process backends (LSP included).  

But all hope is not lost!  With `corfu` + `orderless`, you can have very nice intermediate behavior: _once the completion has begun_ you can filter and refine the (cached) results with full orderless syntax.  This is especially powerful when you get a lot of results (sometimes on purpose, e.g. `import os; os.[M-Tab]`).  

So @minad I hope you stick to your guns on not dumping the CAPF collection on every text change: orderless would be rendered useless for process-based completion systems such as python-mode and LSP!  As pointed out in other discussions, the "intermediate behavior" I mention can lead to incorrect candidates for backends which do not monitor text in the buffer and "self-invalidate".  This is a small problem, and either the UI or the backend can invalidate the cache more intelligently than simply dumping the completion table after every character event (internally, for the backend, or by judiciously refreshing the collection table, for the UI).

**Comment by joaotavora** [comment]
> In the category of "reading meaning into the overly-vague docs" @joaotavora counters with the doctoring of completion-at-point-functions (see this comment):

I haven't read this long thread, but if you mean the `NOTE` at the end of  `completion-at-point-functions`, then I don't understand how it contradicts the rest of the docstring.  I interpret it to  say that (1) requesting a table  table should be cheap  which likely means a functional table and that  (2) that table should ideally be composable with arbitrary completion styles.  I.e.  a big list of slow-to-calculate pre-filtered  stuff should NOT be returned.  

Now to the controversial bit, and the "doctoring": the table to be returned completes the entity between START and END.  Note that this **doesn't** mean it's _wrong_  to return a table that happens to be capable of completing _other_ entities, like that other entity between START2 and END2, as long as it does the right thing for `START`and`END`.  But the docstring doesn't **require** it.   The only requirement is that is  the table must complete what's between `START` and `END`.

And this makes sense.to me:  if someone (the user, via an UI) wants to complete something other than `START` and `END`, she can request it via another table, because, and this is where the `NOTE` becomes relevant, that request is "cheap to run".

Note that for Elisp in particular, which has a single big table of symbols, that table is super cheap to get and completes every "entity" possible in Elisp land, here and there, everywhere.  So if a UI gets this table for Elisp -- it can be the `obarray` object unaltered -- it might use it everywhere and nothing bad ever happens.  Same thing for simple lists of strings. But that UI must not make the mistake of thinking it's like that for every backend. For other backends that aren't as privileged as Elisp, the docstring must be followed more closely to get correct  results. 

In the end there are no miracles: these new  fancy filtering completion styles must be implemented close to source of completions if they are to be fast and accurate, that is, since @jdtsmith seems to be OK with losing some accuracy by adjusting his "mental model" of what is happening.

Anyway for an example:  SLY, a common Lisp IDE,  actually implements `prefix` and `flex` [directly in Common Lisp](https://github.com/joaotavora/sly/blob/540a8c5b9a04af0a6907e07cb070f1fed8a76f48/slynk/slynk-completion.lisp#L88).  A Python IDE would have to do the same, and maybe someday LSP will have provisions for this.

**Comment by jakanakaevangeli** [comment]
> Now, if I patched python.el to compute the completions eagerly, you would
> have to contact the inferior process only once per completion-in-region
> session.

(Just minor a bike-shed warning:)
If by eagerly, you mean in the python-CAPF directly, this will sadly not work:
looking at the function `completion-at-point`, your capf is called from
`completion-in-region-mode-predicate`, which is called from
`post-command-hook`, if using the default completion-in-region function. This
means that you are eagerly recomputing your candidates (using process IO) on
every keystroke (even C-b).

To optimize python completion and reduce IO with the process, you could do the
following:
- Pre-compute the candidates from the string eagerly in the dynamic completion
  table (not in the capf directly).
- Cache the candidates in a (possibly lexical) variable.
- If the user extends the filter string, use the cache. No IO needed.
- It the user shrinks the filter string with DEL, you can recompute the
  candidates with IO.

To accommodate completion styles (such as flex), which pass an empty string to
your dynamic completion table, you could simply check if the string is empty
and fallback to the original input in this case.

**Comment by jdtsmith** [comment]
> Now to the controversial bit, and the "doctoring"

Maybe an accidentally useful word, but that was auto-correct's helpful idea of what "docstring" should read.

**Comment by dgutov** [comment]
> Cache the candidates in a (possibly lexical) variable.

Caching the candidates in a global dynamic variable, with some well-considered invalidation key, will probably work better.

**Comment by jdtsmith** [comment]
> > Cache the candidates in a (possibly lexical) variable.
> 
> Caching the candidates in a global dynamic variable, with some well-considered invalidation key, will probably work better.

I see, I think that was your point on the other discussion, and if this were always true, it would make "completion table dumping" cheap.   But the semantics of "if you notice your cache is invalid, get a new completion table" are pretty decently consistent with a lexical...  BTW, what's an "invalidation key"?  Like, state?

**Comment by jdtsmith** [comment]
> since @jdtsmith seems to be OK with losing some accuracy by adjusting his "mental model" of what is happening.

My mental model is well reinforced by the fact that the first call in such a completion is notably slow since it hits the server/inferior process, with subsequent orderless-driven filtering blazingly fast...

**Comment by astoff** [comment]
@jakanakaevangeli This is so odd! With Corfu or Vertico + `consult-completion-in-region`, the capf is called once, and the dynamic completion table is called once for each keypress. Which sounds pretty reasonable. It's curious that `completion-at-point` is doing all that work... I guess it needs updates on the `START` and `END`?

**Comment by dgutov** [comment]
> But the semantics of "if you notice your cache is invalid, get a new completion table" are pretty decently consistent with a lexical...

It depends on what lexical state one is talking about, but the problem "completion table dumping" has the unfortunate effect of dumping the lexical state associated with the functions returned by c-a-p-f (the completion table and the "extra properties" functions). So if one was storing their cache there, it goes out of the window.

> BTW, what's an "invalidation key"? Like, state?

Some kind of derivative of the buffer state. It's hard to be very precise in an Elisp implementation (with no "real" parser), but one can include the position of the beginning of the prefix, maybe also text from bol until that position, and the first prefix itself, with which the cached completions request was made. Then a cached lookup would first compare the first two values for equality, then compare prefixes (probably by checking that the new is >= long as the initial one, and the first N characters match), and then either filter the cached completions locally, or request new ones.

**Comment by dgutov** [comment]
> It's curious that completion-at-point is doing all that work... I guess it needs updates on the START and END?

In Company, at least, we're calling capf repeatedly to obtain the new values of START and END, yes.

**Comment by astoff** [comment]
> Caching the candidates in a global dynamic variable, with some well-considered invalidation key, will probably work better.

I guess the natural cache invalidation trigger is `completion-in-region-mode-hook`. If Company doesn't call that, I'd say it's very hard to figure out something that works for all frameworks.

**Comment by astoff** [comment]
(FWIW, the Emacs bug I created about this topic is https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50459)

**Comment by dgutov** [comment]
> I guess the natural cache invalidation trigger is completion-in-region-mode-hook. If Company doesn't call that, I'd say it's very hard to figure out something that works for all frameworks.

Suppose you complete a chain of calls, like `foo.bar.baz`. Is `completion-in-region-mode-hook` reliably called every time you type `.`?

**Comment by dgutov** [comment]
> If Company doesn't call that, I'd say it's very hard to figure out something that works for all frameworks.

My point is that the caching is done in the completion backend, using its own specific logic.

Frameworks shouldn't have to know all those details.

**Comment by jdtsmith** [comment]
> It depends on what lexical state one is talking about, but the problem "completion table dumping" has the unfortunate effect of dumping the lexical state associated with the functions returned by c-a-p-f (the completion table and the "extra properties" functions). So if one was storing their cache there, it goes out of the window.

That behavior can be considered a _feature_, if you associate "one completion table instance" with "one fixed state of the buffer".  It sounds like enough backends don't make this association, so company is compelled to ask for new completion tables frequently.

**Comment by dgutov** [comment]
Right.

**Comment by jdtsmith** [comment]
So, we have 3 possible implied contracts, from UI to CAPF:

1. "I will **call you once** and only once per completion-in-region.  It is up to you to monitor for buffer changes and update the results you give me accordingly."
1. "I will **call you rarely** during a completion-in-region.  If I call you again, it's because the buffer has changed and I expect that your collection table is no longer valid." 
1. "I will **call you whenever** and however I want to.  If you have internal state you'd like to save, don't keep it in your collection table."

Oh boy.

**Comment by dgutov** [comment]
FWIW, the scheme I described implies 3, not 2. Though it would usually work with any of 1, 2, 3.

**Comment by oantolin** [comment]
I implemented the `^literal` optimization discussed above. We should probably document a style-dispatcher that adds a `^` to the first component automatically and how to use it for completion-at-point.

**Comment by astoff** [comment]
@dgutov, @jakanakaevangeli What do you think of the following cache invalidation criterium: in a pre-command hook, check if this command is `self-insert-command` and the syntax class is word or symbol. If not, then kill the cache.

I've tested the Python shell completion with company, and it is pretty laggy if the inferior process is running remotely, since each key press triggers a network request. So this might actually be enough justification to change it.

And then orderless will also work OOTB, as a side effect. Please just don't tell anyone about my hidden agenda.

**Comment by jakanakaevangeli** [comment]
Augusto Stoffel ***@***.***> writes:

> @dgutov, @jakanakaevangeli What do you think of the following cache
> invalidation criterium: in a pre-command hook, check if this command
> is `self-insert-command` and the syntax class is word or symbol. If
> not, then kill the cache.

It could work fine, at least with the default
completion-in-region-function, but has some flaws. Example: what if the
user types C-y to paste a ";". This is not a self-insert-command and
cache will not get invalidated.

Another idea for a cache invalidation scheme:
python-shell-CAP calculates completion START (this is fast, only a regex
search). Save it as a marker. From the completion table function,
calculate START again and if it differs from the saved START marker,
invalidate the cache.

**Comment by astoff** [comment]
> This is not a self-insert-command and cache will not get invalidated.

This is not a self-insert-command, so the cache *will* be invalidated. Nevermind it was a false positive.

**Comment by jakanakaevangeli** [comment]
Augusto Stoffel ***@***.***> writes:

> This is not a self-insert-command, so the cache *will* be
> invalidated. Nevermind it was a false positive.

A, sorry, my misunderstanding then. You can disregard my post.

**Comment by minad** [comment]
@oantolin 

> I implemented the ^literal optimization discussed above. We should probably document a style-dispatcher that adds a ^ to the first component automatically and how to use it for completion-at-point.

Is there also a possibility to handle quoted regexps? A style dispatcher could `regexp-quote` the first word and prepend it with ^.

**Comment by dgutov** [comment]
> What do you think of the following cache invalidation criterium: in a pre-command hook, check if this command is self-insert-command and the syntax class is word or symbol. If not, then kill the cache.

It can work, but since the caching would be implemented inside the completion table, I think for it to concern itself with user input and particular invoked commands, is pretty dirty. But you can try and see, IDK.

**Comment by jdtsmith** [comment]
@astoff Why not save and examine the probe text passed into the table (when it is non-empty), updating the cache when the saved probe is not a prefix of the current probe (as I suggested for eglot [here](https://github.com/joaotavora/eglot/pull/737/files))?  

I'm experimenting with it for my ipython mode, and it requires moving cache out of a lexical to a global, due to all the _other_ lambda's that the CAPF creates (like docsig), as well as to handle contract flavor 3 (ala company).  To know when to "start anew" with flavor 3, we can use your idea of `completion-in-region-mode-hook`, dumping the entire global cache there as the mode is disabled.   I _think_ that will then address contract flavors 1, 2, and 3 equally (it's unfortunate that all UI's don't adhere to one of those!).

**Comment by jakanakaevangeli** [comment]
Daniel Mendler ***@***.***> writes:

> Is there also a possibility to handle quoted regexps? A style
> dispatcher could `regexp-quote` the first word and prepend it with ^.

FWIW, here's a correct inverse of regexp-quote (returns nil for values
outside of regexp-quote's codomain.)

(defun regexp-unquote (regex)
  "Return a string passed to `regexp-quote' to produce REGEX.
Return nil, if REGEX couldn't have been produced by `regexp-quote'."
  (unless (string-match-p "[$*+.?[\\^]"
                          (replace-regexp-in-string "\\\\[$*+.?[\\^]" "" regex
                                                    'fixedcase 'literal))
    (replace-regexp-in-string "\\\\\\([$*+.?[\\^]\\)" "\\1" regex
                              'fixedcase)))

**Comment by minad** [comment]
@jakanakaevangeli Great, I was looking before if `regexp-unquote` exists in Emacs. Thanks for providing it! @oantolin What about using it to make the prefix optimization more general, such that quoted regexps are also supported?

**Comment by oantolin** [comment]
Sure, why not, @minad? But I'm not sure it's necessary. Thanks for the `regexp-unquote` function, @jakanakaevangeli!

**Comment by minad** [comment]
@oantolin this allows a simpler dispatcher which just takes the first word, quotes it and prepends it with ^. In the current implementation, this will only work for non-regexp characters. But sure, it is an edge case.

**Comment by astoff** [comment]
Okay, there are two topics in parallel now. We should start using mailing lists, like the pros.

I'll reply to @jdtsmith's last comment here, but maybe we should continue discussing the performance/caching issue at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50459

My criterium is pretty simple and has no false negatives (i.e., it never misses invalidating the cache when needed). But now I realize that there are a few false positives that can be mildly problematic. E.g., when the user presses TAB.

I think (a slight refinement of) your suggestion makes sense, specially for reasonably dumb comint-based capf. In Eglot, where the completion is more context-sensitive, there can be weird edge cases too. Imagine, in Lisp, that I try to complete "(x" (a function starting with x), then delete the parenthesis and try to complete "x" (a variable starting with x). Adding a marker as additional  safeguard doesn't help either. But this doesn't seem a very common thing to happen anyway.

**Comment by jdtsmith** [comment]
Yeah, that's an issue; you could also be crazy and put your region inside a string in mid-completion (change `os.li` to `"os.li`) in which case the entire completion becomes invalid.  I guess to guard the probe-prefix invalid trick you could add "line is unchanged before the current completion region", which I believe @dgutov suggested.  But note that some UI's (like corfu and company) actually _kill_ the completion if you try to go back and edit before the completion text.   So a non-issue for them.  

In terms of invalidation to handle all the cases 1,2,3, it gets complicated.  I'm thinking it may be necessary to accept all the "frequent table dumping" of contract flavor 3 as false positives.  Just kill the cache and start over (unnecessarily, sometimes, but oh well).  For flavors 1 & 2, table dumps are true positive invalidations.  Flavor 1 requires additional _in media res_ invalidations too.

**Comment by astoff** [comment]
Okay, I tested @jdtsmith's idea for the cache invalidation and it seems to work well. I submitted a patch to the Emacs bug linked above, in case anyone wants to take a look.

**Comment by astoff** [comment]
It now occurred to me that in the ^literal case, it would be possible to support completion of a common prefix substring. The effect wouldn't be too different from `(setq completion-styles '(basic orderless))`, so I don't know if it's something worth doing.

In any case, I'll close the issue, because now the Python completion table does caching (which is kind of important when the shell is remote) and therefore works with orderless as a side effect.

**Comment by minad** [comment]
@astoff there are two reasons to still do the prefix special casing.

1. It allows optimized filtering
2. It allows orderless filtering for input strings like "prefix word2 word3", which would not work with `basic`+`orderless`

However you are right that `basic`+`orderless` is almost an equivalent and sufficient solution. I already pointed this out in the beginning of the discussion.

**Comment by astoff** [comment]
@minad Sure, I understand that part — I've learned some things in this long discussion :-)

But I was referring to something else, namely the common prefix insertion feature (`b<tab>` becomes `ba` if the candidates are `foo`, `bar` and `baz`).

My point was that while this feature doesn't make sense in the regular orderless style, it could be implemented for the “mostly orderless” style, since changing the query from `^b` to `^ba` doesn't change the list of matching candidates.

**Comment by minad** [comment]
@astoff Okay. Indeed it would be possible to support TAB common prefix completion. I think it is worth doing this if the `mostly-orderless` style aims to be a full substitute for `basic`+`orderless`.

**Comment by oantolin** [comment]
Oh, good point @astoff! We could have TAB do something useful now.
