### ISSUE TITLE
Prefer the most frequent candidates with ordereless in company-mode

### ISSUE THREAD

**Issue by rememberYou** [oantolin/orderless#80]
First of all, thanks for `orderless`! 

I'm opening this issue because when I use `orderless` with `company-mode`, I can't get `orderless` to highlight the most recently (or frequently) used commands in the candidate list. However, `orderless` works well with `vertico` and `execute-extended-command` (`M-x`) where the most recently used commands are put above.

Is it possible to adopt this behavior with `company-mode`? For comparison, when I use `company-prescient`, I have exactly this desired behavior. However, I would be sad if I should use `orderless` to sort and filter the completion in minibuffer and `company-prescient` to adapt this behavior with `company-mode`.

With `orderless`:

![2021-09-09-103920](https://user-images.githubusercontent.com/6253527/132653238-7a0bb44e-7000-44cb-8f5c-07549629f2a8.png)

![2021-09-09-103934](https://user-images.githubusercontent.com/6253527/132653266-4e37eb11-5025-49b4-be02-e32813c30b9a.png)

With `company-prescient`:

![2021-09-09-103951](https://user-images.githubusercontent.com/6253527/132653313-7f9b7616-c4e9-45e0-9faa-1658566eb389.png)

![2021-09-09-103956](https://user-images.githubusercontent.com/6253527/132653329-6011336f-fc32-4027-bd83-66cc6de66bbb.png)

Here we see that the `onanimationcancel` variable is proposed above the list because I have just used it.

Finally, this is how I define `orderless` in my GNU Emacs config.
```elisp
(use-package orderless
  :custom
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles . (initials)))))
  (completion-styles '(orderless)))
  ```

**Comment by oantolin** [comment]
orderless does no sorting at all! Vertico does it's own sorting by recency, which is why you see that behavior in Vertico. I'm a little surprised company doesn't do any sorting (which seems to be what your are saying). I don't use company myself, so it will be a little hard for me to help, but you should be able to use orderless for filtering and prescient just for sorting.

**Comment by rememberYou** [comment]
I had a doubt despite the explicit name of the package :-)

 Thanks for your answer. I will probably use `company-prescient` for `company-`mode which seems to be more suitable for this behavior.
