### ISSUE TITLE
orderless completing text in the minibuffer with M-:

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/orderless#82]
When building expressions in the minibuffer with `M-:`, elisp completion is naturally used.  But obviously in this context you can't get complete-in-region style popups, nor use the minibuffer itself for completion.  So completion falls back on the `*Completions*` buffer, which is fine.   But with completion-styles of say `'(orderless partial-completion)` you get no common-prefix expansion, only highlighting of the match parts.  Maybe turning orderless off for `M-:` is the right call, but I can't find any "category" that would apply to that completion environment.  Is there an obvious solution here I'm missing?  Do people all just add `'basic` to the end of their default completion-styles?

Thanks for orderless.

**Comment by oantolin** [comment]
> But obviously in this context you can't get complete-in-region style popups

You can with Corfu. I think it doesn't apply to completion-in-region from the minibuffer by default, but you can configure it to do so.

> nor use the minibuffer itself for completion

Sure you can. I use `consult-completion-in-region` from `M-:`. I don't like `consult-completion-in-region` for most cases of completion-in-region in the minibuffer, but make an exception specifically for `eval-expression`. My configuration is as follows:

```elisp
(setq completion-in-region-function #'consult-completion-in-region)

(defun choose-completion-in-region ()
    "Use default `completion--in-region' unless we are in `eval-expression'."
    (unless (eq this-command 'eval-expression)
      (setq-local completion-in-region-function #'completion--in-region)))

(add-hook minibuffer-setup-hook #'choose-completion-in-region)
```

**Comment by oantolin** [comment]
> But with completion-styles of say `'(orderless partial-completion)` you get no common-prefix expansion.

You would get prefix expansion with the opposite order: `'(partial-completion orderless)`.

> Maybe turning orderless off for `M-:` is the right call, but I can't find any "category" that would apply to that completion environment.

There is no specific category for symbol completion _when it happens to be during `eval-expression`_. What I suggest you do instead, if you want to change completion styles, is to use a minibuffer-setup-hook that checks to see if `this-command` is `eval-expression` (see the function for a similar purpose shown above). Use `setq-local` to change the completion style so that the minibuffer exit cleans up you changes for you.

**Comment by jdtsmith** [comment]
> > But obviously in this context you can't get complete-in-region style popups
> 
> You can with Corfu. I think it doesn't apply to completion-in-region from the minibuffer by default, but you can configure it to do so with `(add-hook 'minibuffer-setup-hook #'corfu-mode)`.

Aha!  A revelation, and an excellent demonstration of how child frames can be superior to overlays.  Nice enough I think to make a default, @minad.  Very nice, thanks.

**Comment by minad** [comment]
I prefer the `*Completions*` buffer for completion in the minibuffer, but yes, Corfu works well there too.

**Comment by jdtsmith** [comment]
> I prefer the `*Completions*` buffer for completion in the minibuffer, but yes, Corfu works well there too.

Thanks.  Can I inquire what completion-styles order you use, and if you alter it for the minibuffer?

**Comment by oantolin** [comment]
> I prefer the `*Completions*` buffer for completion in the minibuffer, but yes, Corfu works well there too.

Really? I'm surprised, I would have thought you stuck with Vertico, through `consult-completion-in-region`.

**Comment by minad** [comment]
No, I am not using consult-completion-in-region. I don't like that it opens a recursive minibuffer. I am not using any special style only orderless.

**Comment by minad** [comment]
Do you use M-: often? Either one has already typed the expression one and just repeats it from history, or one made a command. Then there are also commands like `set-variable`.

**Comment by oantolin** [comment]
> I don't like that it opens a recursive minibuffer in this case

Yeah, it is a little awkward that you can't see the spot where you were completing.

I don't use `M-:` very often either.

**Comment by jdtsmith** [comment]
> Do you use M-: often? Either one has already typed the expression one and just repeats it from history, or one made a command. Then there are also commands like `set-variable`.

I do use it often, because it has session-persistent history (with `savehist`).  For example, I often find I'd like to trace a function and include a backtrace at the same time.  I know in my `M-:` history I can `C-r` (or `consult-history`!) and find things like `(trace-function #'font-lock-fontify-region nil (lambda () (backtrace-to-string (backtrace-get-frames 'backtrace))))`.  

Probably I should use an org mode file or something to save these kinds of one-offs proactively, but this works pretty well for short but "more complex than a command" snippets I've been using recently, and is really quick to access.  I also have a lot of things like `(setq completion-styles '(basic orderless partial-completion))` when I'm testing completion ;).  

One interesting idea would be to save a history of "things you evaluated in `*scratch*`", with consult-history searching, naturally.  Other approaches?
