### ISSUE TITLE
Is there a way to disable orderless for a specific command?

### ISSUE THREAD

**Issue by ogdenwebb** [oantolin/orderless#86]
I want to have blacklist for some commands. The reason why I'm asking because [go-impl](https://github.com/emacsorphanage/go-impl) is working pretty poorly when Vertico enabled with orderless.

**Comment by oantolin** [comment]
You can always use `:around` advice to let-bind `completion-styles` to whatever you want:

```elisp
(defun without-orderless (fn & rest args)
  (let ((completion-styles '(basic partial-completion)))
    (apply fn args)))

(advice-add 'command-which-should-not-use-orderless
            :around #'without-orderless)
```

An alternative approach, if the command you want to turn orderless off for has some special completion category `foo`, is to add an entry to the `compeltion-category-overrides` alist for the key `foo`. This does not disable orderless, but gives priority to the completion styles in the overrride list and this may be enough.

**Comment by ogdenwebb** [comment]
Sadly `without-orderless` has no impact on go-impl. Not sure what's wrong, but even with this advice for go-impl orderless seems somehow affects the logic of "." in completion. For example when I type "io." to get all interfaces from io package. 

Normal completion
![normal](https://user-images.githubusercontent.com/9018005/136076922-2d829e30-aba6-4d17-aa41-b845da62a894.png)

With orderless
![orderless](https://user-images.githubusercontent.com/9018005/136076950-39c48bbc-1747-4dd9-b77a-d14bde8a17e5.png)

**Comment by oantolin** [comment]
Sorry, I missed your response! This is hard for me to test since I don't use Go and I don't think one can really test the `go-impl` package without a whole Go installation. But looking at the go-impl source code, I'd say probably the advice should go on `go-impl--completing-function`, not directly on `go-impl`. Give that a shot.

**Comment by ogdenwebb** [comment]
Don't worry. In the past I tried to advice `go-impl--completing-function` as well, but it gave me an error when I call `M-x go-impl` - something related to Vertico.

I didn't use Emacs too much recently, but I've just tested it now without this advice and looks like now Vertico can handle that correctly.
