### ISSUE TITLE
Issue with cider complete

### ISSUE THREAD

**Issue by benjamin-asdf** [oantolin/orderless#89]
Hi, 
my issue is for completing when the prefix is "foo/" (with `/` in the name). Somehow `orderless-filter` only decides to call the completing function  with the empty string but never with "foo/" which would yield the correct completions. 
Do you know why and can you help me fix this in some way? 
Thanks for the awesome package.

If you need a repro I can check if I can make a minimal one.

**Comment by minad** [comment]
See https://github.com/clojure-emacs/cider/issues/3019

**Comment by abcdw** [comment]
I can't reproduce it. Can someone else check it the problem is still present?

**Comment by minad** [comment]
Using basic as fallback is perfectly fine for dynamic tables.

**Comment by abcdw** [comment]
I did the following trick, which is a little dirty, but works quite well: https://github.com/clojure-emacs/cider/issues/3019#issuecomment-1333921798

![image](https://user-images.githubusercontent.com/1218615/205088664-39e42197-cf5d-4551-9334-f00c29bb0e21.png)
![image](https://user-images.githubusercontent.com/1218615/205088771-25c1b05e-3d91-4365-ad71-f2740c63b44c.png)
