### ISSUE TITLE
About the completion results given by orderless.

### ISSUE THREAD

**Issue by hongyi-zhao** [oantolin/orderless#90]
On Ubuntu 20.04.3 LTS, I use the following configuration for orderless:

```emacs-lisp
(use-package orderless
  :init (icomplete-mode)
  :custom (completion-styles '(orderless)))
```
When I use swiper to search the minibuffer with "com delay", the results are shown below:

![image](https://user-images.githubusercontent.com/11155854/138082642-40e8dc52-b645-4316-80de-f7ccee3b088a.png)

According to my understanding, the results should also contain the ones which include substring "delay" appeared before substring "com", am I right?

Regards,
HZ

**Comment by Eason0210** [comment]
@hongyi-zhao  I set as follow , and got the result as expected.
```emacs-lisp
(use-package orderless
  :hook (minibuffer-setup . sanityinc/use-orderless-in-minibuffer)
  :config
  (setq completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion))))
  :preface
  (defun sanityinc/use-orderless-in-minibuffer ()
    (setq-local completion-styles '(substring orderless))))
```

**Comment by hongyi-zhao** [comment]
> sorry, i didn't mention that I was using the [vertigo](https://github.com/minad/vertico) . 

It's called vertico. BTW, I've learned that [corfu](https://github.com/minad/corfu) is often used in companion with [vertigo](https://github.com/minad/vertico). 

> Actually, i also use [ consult](https://github.com/minad/consult)

Does consult supplies the similar function as that in [counsel](https://github.com/abo-abo/swiper/blob/master/counsel.el)?

> And you can see details in [my personal Emac config ](https://github.com/Eason0210/dot-emacs/blob/d3d1410c936e4391fdaaa71f56db12c5140f2ac3/init.el#L260)

I'm currently using the following `ivy/counsel/swiper` relevant configuration:

```emacs-lisp
(use-package swiper
  :bind ("C-s" . swiper))
  

(use-package ivy
  :diminish ivy-mode
  :init
  (ivy-mode +1)
  )

(use-package counsel
  :diminish counsel-mode
  :after helpful
  :init (setq ivy-use-selectable-prompt t
              search-default-mode #'char-fold-to-regexp
              counsel-describe-function-function #'helpful-callable
              counsel-describe-variable-function #'helpful-variable)
  :bind (("C-x C-f" . counsel-find-file)
	 ;;https://github.com/abo-abo/swiper/issues/2888#issuecomment-874893794
         ("C-x 8 RET" . counsel-unicode-char)
         ("<f4>" . counsel-bookmark)
         ("s-4" . counsel-bookmark)
         ("s-r" . counsel-recentf))
  :config (counsel-mode 1)
  (defalias 'recent 'counsel-recentf))
(define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)


;;https://github.com/alexmurray/ivy-xref#installation
(use-package ivy-xref
  :init
  ;; xref initialization is different in Emacs 27 - there are two different
  ;; variables which can be set rather than just one
  (when (>= emacs-major-version 27)
    (setq xref-show-definitions-function #'ivy-xref-show-defs))
  ;; Necessary in Emacs <27. In Emacs 27 it will affect all xref-based
  ;; commands other than xref-find-definitions (e.g. project-find-regexp)
  ;; as well
  (setq xref-show-xrefs-function #'ivy-xref-show-xrefs))


(use-package ivy-rich
  :custom
  (ivy-virtual-abbreviate 'full)
  (ivy-rich-switch-buffer-align-virtual-buffer nil)
  (ivy-rich-path-style 'full)
  :config
  (setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line)
  (ivy-rich-mode 1))


;;https://github.com/daviwil/emacs-from-scratch/wiki/Counsel-insert-relative-file-path#insert-relative-file-path-in-current-buffer-using-counsel
;;Useful while inserting figures path/name in latex. Similar to C-x C-f in vim.
(defun try/counsel-insert-file-path ()
  "Insert relative file path in current buffer using counsel in minibuffer"
  (interactive)
  (unless (featurep 'counsel) (require 'counsel))
  (ivy-read "Insert filename: " 'read-file-name-internal
            :matcher #'counsel--find-file-matcher
            :action
            (lambda (x)
              (insert (file-relative-name x)))))
;;Recommended keybinding setting
(general-create-definer try/ctrl-c-keys
  :prefix "C-c")

(try/ctrl-c-keys
  "i"   '(try/counsel-insert-file-path :which-key "insert relative filepath"))
```
I'm still not sure about the corresponding configuration implemented with `consult/vertico/corfu/orderless`.

**Comment by hongyi-zhao** [comment]
@oantolin 
> It is possible to use orderless with Ivy, and you can find instructions on how to configure that in the orderless README.

I tried with and without ` :init (icomplete-mode)`, but obtained different search results, as shown below:

```emacs-lisp
(use-package orderless
  :init (icomplete-mode)
  :config
  (setq ivy-re-builders-alist '((t . orderless-ivy-re-builder)))
  :custom (completion-styles '(orderless)))
```
![image](https://user-images.githubusercontent.com/11155854/138195884-a2391d64-0363-4f0a-b199-6ac5c960dfa4.png)


```emacs-lisp
(use-package orderless
  :config
  (setq ivy-re-builders-alist '((t . orderless-ivy-re-builder)))
  :custom (completion-styles '(orderless)))
```
![image](https://user-images.githubusercontent.com/11155854/138196008-71d74f79-7e95-44df-803a-8fb954322d16.png)

Any hints for this phenomenon?

**Comment by hongyi-zhao** [comment]
I still feel confused about the following things:

1. Is the `icomplete-mode` is supplied by [icomplete-vertical](https://github.com/oantolin/icomplete-vertical) package?
2. What are the advantages and disadvantages of `Icomplete` and `Ivy`?

**Comment by oantolin** [comment]
No, the `icomplete-vertical` package supplies a mode called `icomplete-vertical-mode`. There is a package I wrote with that name and in the development version of Emacs, Emacs 28, there is another package of the same name with very similar functionality (that I had nothing to do with).

The `icomplete-mode` mode you mentioned is provided by the built-in `icomplete` package. It displays completion candidates horizontally instead of vertically like Ivy.

The list of advantages and disadvantages are somewhat subjective, but definitely the main difference is that Icomplete displays candidates in a horizontal manner and Ivy shows them vertically. But of course there is icomplete-vertical if you want something like Icomplete but want a vertical display.

Another big difference is that Icomplete respects the Emacs settings for completion-styles, while Ivy does not use completion-styles and instead has it's own matching logic.

I think really the only way to know what you prefer is to try both.
