### ISSUE TITLE
Enable orderless for company-search-mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [oantolin/orderless#92]
The [company-search-mode](https://github.com/company-mode/company-mode/blob/297620caf84f771a7102157f1bf292e5b248e397/company.el#L2411-L2431) can search completion candidates incrementally, as shown below:

![image](https://user-images.githubusercontent.com/11155854/138558478-744c4d82-f9dd-4c3a-bc00-86b86e853b8e.png)

In the above screenshot, I first input `doc`, then run the `company-search-candidates` command on the completion candidates to search them incrementally, taking an example by string `cla` here. But this method only let me filter the candidates by a non-space string. I want to search the candidates with `orderless` based on multiple space-separated substrings, just as the thing done in `minibuffer`. 

Is this possible? Any hints will be greatly appreciated.
 
Regards,
HZ

**Comment by minad** [comment]
I've searched the Company issue tracker for completion style support for company-search-mode, but this does not seem to exist yet. Completion style support (or at least support for a custom regexp compiler) would be needed for Orderless to integrate there. Please ask on the [Company forum](https://github.com/company-mode/company-mode/discussions) about this.
