### ISSUE TITLE
orderless-regexp end of line matching with dollar `$` not working.

### ISSUE THREAD

**Issue by mohkale** [oantolin/orderless#93]
I'm not sure why but when using orderless and `consult-line` if I enter a query like `foo$` I get no results, even if there are lines ending with foo. Using orderless without any other configuration `(orderless-pattern-compiler "foo$")` gives `("\\(?:foo\\$\\|foo$\\)")` which should match the end of a line, but doesn't.

For what its worth `^foo` does work (using `^` to match the beginning of the line).

**Comment by minad** [comment]
Documented in https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer

**Comment by mohkale** [comment]
@minad 

Ah, that makes sense. Is there a comprehensive list of functions that behave like this in consult or is this a fix as you encounter situation?

**Comment by minad** [comment]
Yes, the wiki solution works always, independent on if the command uses tofus (unicode tofu disambiguation suffixes) or not. Therefore I also consider the problem to be solved now. I was initially worried by the tofus and I was looking for a better solution. I thought about extending the completing-read API such that it directly allows candidate disambiguation or preserves object identity.
