### ISSUE TITLE
Mention Corfu

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/orderless#99]
[Corfu](https://github.com/minad/corfu) works great out of the box with orderless, even supporting spaces in the buffer to separate match terms.  In fact orderless is the strongly recommended style for using LSP-mode with corfu (see [Wiki](https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-mode-with-orderless)).  Worth a mention in the README!  And as a bonus, orderless colors look good with corfu + [kind-icon](https://github.com/jdtsmith/kind-icon).

**Comment by oantolin** [comment]
I added a paragraph to the overview about completion at point, mentioning Corfu, Company and `consult-completion-in-region`.
